  <div class="bgimg">
      <div class="div-quiz-left" >
        <div class="left-quiz-inside">
          <p class="vertical-quiz-title">GIFT CARDS</p>
        </div>
      </div>
      <div class="div-inline-center">
        <p class="quiz-medium-tilte">WHAT'S YOUR EARNING SCORE</p>
        <div class="div-center-text">
            <p class="quiz-short">WE'RE CONVINCED THAT SOCIALIZED COMMERCE, POWERED BY TRUNITED.COM, CAN TAKE YOUR</p>
            <p class="quiz-short">BUYING POWER AND PUT THAT MONEY TO WORK FOR YOU. LET'S TAKE JUST A FEW THINGS AND</p>
            <p class="quiz-short">PUT THAT CLAIM TO THE TEST.</p>
            <hr class="orange">
            <p class="quiz-medium">Which Of These Gift Card Brands Would You Buy?</p>
          </div>
        <div class="btn-all-div">
        <div class="div-center-products">
          <form  action="score-giftcards" method="post" id="change-form" role="form">
          <div class="div-centered">
            


              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/1_1_BucaDiBeppo.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/1_2_AMCAmazing.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/2_1_BuffaloWings.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/2_2_ColdStone.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/3_1_BurguerKing.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/3_2_Roys.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/4_1_Applebes.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/4_2_DunkinDonuts.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/5_1_RedRobin.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/5_2_KrispyKreme.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/6_1_SmashBurguer.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/6_2_NutriSystem.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/7_1_Logans.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/7_2_KonaGrill.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/8_1_JiffyLube.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/8_2_Trunited.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/9_1_CircleK.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/9_2_CoffeBean.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/10_1_PFChangs.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/10_2_Starbucks.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/11_1_LuluLemon.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/11_2_Nordstrom.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/12_1_Ebay.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class=" div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GiftCards_icons/12_2_GameStop.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
           
          </div>
             
              &nbsp;
             
              &nbsp;
            
            <div>
                <input type="hidden" name="result" id="mytext">
                <div class="div-button-center">
                    <input class="input-shop-join" type="submit" value="GET MY SCORE!" />
                </div>
            </div>
             <br>
              &nbsp;
              <br>
              &nbsp;
              <br>
              &nbsp;
              <br>
              &nbsp;
              <br>
              &nbsp;
            </form>
            </div>
        </div>   
      </div>
</div>