  <div class="bgimg">      
      <div class="div-quiz-left" >
        <div class="left-quiz-inside">
          <p class="vertical-quiz-title">GLOBAL BRANDS</p>
        </div>
      </div>
      <div class="div-inline-center">
        <p class="quiz-medium-tilte">WHAT'S YOUR EARNING SCORE</p>
          <div class="div-center-text">
            <p class="quiz-short">WE'RE CONVINCED THAT SOCIALIZED COMMERCE, POWERED BY TRUNITED.COM, CAN TAKE YOUR</p>
            <p class="quiz-short">BUYING POWER AND PUT THAT MONEY TO WORK FOR YOU. LET'S TAKE JUST A FEW THINGS AND</p>
            <p class="quiz-short">PUT THAT CLAIM TO THE TEST.</p>
            <hr class="orange">
            <p class="quiz-medium">Which Of These Global Brands Do You Shop?</p>
          </div>
        <div class="btn-all-div">
          <form  action="score-global" method="post" id="change-form" role="form">
            <div class="div-centered">
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/1_1_VitaminShoppe.png') ?>" alt="Divided we fall, Trunited we stand">
                   <p class="short"></p>
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/1_2_VistaPrint.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/1_3_ClassPass.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/1_4_TrueValue.png') ?>" alt="Divided we fall, Trunited we stand">
              </div> 
               <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/2_1_SuLaTable.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/2_2_ScrubsBeyond.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/2_3_StitchFix.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/2_4_MilitarySupply.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
               <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/3_1_Staples.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/3_2_Quill.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/3_3_PriceLine.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/3_4_24HourFitness.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
               <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/4_1_Payless.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/4_2_Timex.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/4_3_SharperImage.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/4_4_Microsoft.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/5_1_Speck.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/5_2_BestBuy.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/5_3_SteinMart.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/5_4_Baskets.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
               <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/6_1_Bloomingdales.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/6_2_CampingWorld.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/6_3_LendingTree.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
              <div class="btn-under-label">
                   <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/GlobalBrands_icons/6_4_DylansCandyBar.png') ?>" alt="Divided we fall, Trunited we stand">
              </div>
            </div>
             
              &nbsp;
              <input type="hidden" name="result" id="mytext">
                <div class="div-button-center">
                    <input class="input-shop-join" type="submit" value="GET MY SCORE!" />
                </div>
             <br>
              &nbsp;
              <br>
              &nbsp;
              <br>
              &nbsp;
              <br>
              &nbsp;
              <br>
              &nbsp;
              <tr></tr>
            </form>
        </div>   
      </div>
</div>