<div class="bgimg">
      <div class="div-quiz-left" >
        <div class="left-quiz-inside">
          <p class="vertical-quiz-title">MONTHLY SERVICES</p>
        </div>
      </div>
      <div class="div-inline-center">
        <p class="quiz-medium-tilte">WHAT'S YOUR EARNING SCORE</p>
        <p class="quiz-short">WE'RE CONVINCED THAT SOCIALIZED COMMERCE, POWERED BY TRUNITED.COM, CAN TAKE YOUR</p>
        <p class="quiz-short">BUYING POWER AND PUT THAT MONEY TO WORK FOR YOU. LET'S TAKE JUST A FEW THINGS AND</p>
        <p class="quiz-short">PUT THAT CLAIM TO THE TEST.</p>
        <hr class="orange">
        <p class="quiz-medium">Which Of These Monthly Services Do You Use?</p>
        <div class="btn-all-div">
          <form  action="score-monthly" method="post" id="change-form" role="form">

          <div class="div-centered">

              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/1_1_AutoInsurance.png') ?>" alt="Divided we fall, Trunited we stand">
                   <p class="short">AUTO INSURANCE</p>
              </div>

              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/1_2_LifeInsurance.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">LIFE INSURANCE</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/1_3_HomeInsurance.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">HOME INSURANCE</p>          
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/1_4_TravelInsurance.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">TRAVEL INSURANCE</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/1_5_PetInsurance.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">PET INSURANCE</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/2_1_PetGrooming.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">PET GROOMING</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/2_2_Landscaping.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">LANDSAPING</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/2_3_Housekeeping.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">HOUSEKEEPING</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/2_4_Laundry.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">LAUNDRY SERVICES</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/2_5_PoolCleaning.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">POOL CLEANING</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/3_1_Handyman.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">HANDYMAN</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/3_2_Plumber.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">PLUMBER</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/3_3_HVAC.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">HVAC</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/3_4_DryCleaning.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">DRY CLEANING</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/3_5_PestControl.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">PEST CONTROL</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/4_1_AlarmSecurity.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">ALARM SECURITY</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/4_2_ChildCare.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">CHILD CARE</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/4_3_BarberShop.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">BARBER SHOP</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/4_4_HairSalon.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">HAIR SALON</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/4_5_Nails.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">NAILS</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/5_1_Grooming.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">GROOMING</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/5_2_Massages.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">MASSAGES</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/5_3_Assisting.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">ASSISTING</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/5_4_Accounting.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">ACCOUNTING</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/5_5_Lending.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">LENDING</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/6_1_RealEstate.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">REAL ESTATE</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/6_2_HealthcarePlans.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">HEALTHCARE PLANS</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/6_3_HealthCare.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">HEALTH CARE</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/6_4_Prescriptions.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">PRESCRIPTIONS</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" src="<?php echo $this->getSkinUrl('images/inode/quizzes/MonthlyServices_icon/6_5_Concierge.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">CONCIERGE</p>
              </div>

              </div>
             
              &nbsp;
              <input type="hidden" name="result" id="mytext">
                <div>
                    <input class="input-shop-join" type="submit" value="GET MY SCORE!" />
                </div>
             <br>
              &nbsp;
              <br>
              &nbsp;
              <br>
              &nbsp;
              <br>
              &nbsp;
              <br>
              &nbsp;
            </form>
        </div>   
      </div>
</div>