  <div class="bgimg">
      <div class="div-quiz-left" >
        <div class="left-quiz-inside">
          <p class="vertical-quiz-title">EVERYDAY PRODUCTS</p>
        </div>
      </div>
       
      <div class="div-inline-center">
        <p class="quiz-medium-tilte">WHAT'S YOUR EARNING SCORE</p>
        <div class="div-center-text">
          <p class="quiz-short">WE'RE CONVINCED THAT SOCIALIZED COMMERCE, POWERED BY TRUNITED.COM, CAN TAKE YOUR</p>
          <p class="quiz-short">BUYING POWER AND PUT THAT MONEY TO WORK FOR YOU. LET'S TAKE JUST A FEW THINGS AND</p>
          <p class="quiz-short">PUT THAT CLAIM TO THE TEST.</p>
          <hr class="orange">
            
          <p class="quiz-medium">Which Of These Everyday Products Do You Use?</p>
        </div>
        
        <div class="btn-all-div">
          <form  action="score-d2c" method="post" id="change-form" role="form">
          <div class="div-centered">
            
              <div class="btn-under-label">
                  <img class="div-image-left"  src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/1_1_LaundrySoap.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">LAUNDRY SOAP</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-dish-soap" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/1_2_DishSoap.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">DISH SOAP</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-hand-soap" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/1_3_HandSoap.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">HAND SOAP</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-stain-remover" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/1_4_StainRemover.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">STAIN REMOVER</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-baby-wipes" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/1_5_BabyWipes.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">BABY WIPES</p>
              </div>
 
               <div class="btn-under-label">
                  <img class="div-image-left" name="answer-paper-towels" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/2_1_PaperTowels.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">PAPER TOWELS</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-body-soap" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/2_2_BodySoap.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">BODY SOAP</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-bee-jerky" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/2_3_BeeJerky.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">BEEF JERKY</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-baby-lotion" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/2_4_BabyLotion.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">BABY LOTION</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-deodorant" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/2_5_Deodorant.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">DEODORANT</p>
              </div>

              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-energy-drinks" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/3_1_EnergyDrinks.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">ENERGY DRINKS</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-tooth-paste" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/3_2_Toothpaste.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">TOOTHPASTE</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-shampoo" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/3_3_Shampoo.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">SHAMPOO</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-conditioner" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/3_4_Conditioner.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">CONDITIONER</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-body-wash" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/3_5_BodyWash.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">BODYWASH</p>
              </div>

               <div class="btn-under-label">
                  <img class="div-image-left" name="answer-facial-cleanser" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/4_1_FacialCleanser.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">FACIAL CLEANSER</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-daily-vitamin" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/4_2_DailyVitamin.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">DAILY VITAMINS</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-protein-shake" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/4_3_ProteinShake.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">PROTEIN SHAKE</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-body-lotion" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/4_4_BodyLotion.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">BODY LOTION</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-coffe" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/4_5_Coffe.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">COFFEE</p>
              </div>

              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-snacks" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/5_1_Snacks.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">SNACKS</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-candy" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/5_2_Candy.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">CANDY</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-chewing-gum" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/5_3_ChewingGum.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">CHEWING GUM</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-facial-serum" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/5_4_FacialSerum.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">FACIAL SERUM</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-eye-cam" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/5_5_EyeCream.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">EYE CREAM</p>
              </div>

              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-protein-bars" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/6_1_ProteinBars.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">PROTEIN BARS</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-medication" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/6_2_OTCMedication.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">OTC MEDICATION</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-suplements" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/6_3_Supplements.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">SUPPLEMENTS</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-protein-powder" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/6_4_ProteinPowder.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">PROTEIN POWDER</p>
              </div>
              <div class="btn-under-label">
                  <img class="div-image-left" name="answer-house-cleanser" src="<?php echo $this->getSkinUrl('images/inode/quizzes/DailyProducts_icons/6_5_HouseCleaner.png') ?>" alt="Divided we fall, Trunited we stand">
                  <p class="short">HOUSE CLEANER</p>
              </div>
                </div>
             
              &nbsp;
              <input type="hidden" name="result" id="mytext">
                <div class="div-button-center">
                    <input class="input-shop-join" type="submit" value="GET MY SCORE!" />
                </div>
             <br>
              &nbsp;
              <br>
              &nbsp;
              <br>
              &nbsp;
              <br>
              &nbsp;
              <br>
              &nbsp;
            </form>
        </div>   
          
      </div>
</div>
