<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 *
 * @package     Skrill
 * @copyright   Copyright (c) 2014 Skrill
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * 
 */
?>
<?php
	$langs = Mage::helper('skrill')->getLocaleIsoCode(); 
	switch ($langs) {
		case 'de':
		  $lang = $langs;
		  break;

		default:
		  $lang='en';
	}
?>
<script src="<?php echo Mage::getSingleton('customer/session')->getJsUrl().$lang;?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('js/skrill/jquery-1.10.2.min.js')?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('js/skrill/skrill_cc.js')?>" type="text/javascript"></script>
<link href="<?php echo $this->getSkinUrl('css/skrill/formbank.css')?>" rel="stylesheet" type="text/css">

<form action="<?php echo Mage::getSingleton('customer/session')->getIframeFrontendResponse();?>" id="<?php echo Mage::getSingleton('customer/session')->getIframeToken();?>"><?php echo Mage::getSingleton('customer/session')->getIframeCardBrand();?></form>
<input class="cust_name" value="<?php echo Mage::getSingleton('customer/session')->getIframeName();?>" type="hidden">
<input class="card_list" value="<?php echo Mage::getSingleton('customer/session')->getIframeCardBrand();?>" type="hidden">
<input class="img_url" value="<?php echo $this->getSkinUrl('images/skrill');?>" type="hidden">

<?php
	if ($lang == "de")
	{
		echo '<a class="linkskrill" href="http://www.skrill.com/de" target="blank">';
		echo '<a class="linkskrilloverlay" href="http://www.skrill.com/de" target="blank">';
	}
	else
	{
		echo '<a class="linkskrill" href="http://www.skrill.com/en" target="blank">';
		echo '<a class="linkskrilloverlay" href="http://www.skrill.com/en" target="blank">';
	}
?>

<span class="txtSSL"><?php echo Mage::helper('skrill')->__('FRONTEND_PAYMENT_SSL'); ?></span>
<span class="txtCardNumber"><?php echo Mage::helper('skrill')->__('FRONTEND_CC_NUMBER') ?></span>
<span class="txtExpires"><?php echo Mage::helper('skrill')->__('FRONTEND_CC_EXPIRY') ?></span>
<span class="txtCvc"><?php echo Mage::helper('skrill')->__('FRONTEND_CC_CVC') ?></span>
<span class="txtHelp"><?php echo Mage::helper('skrill')->__('FRONTEND_CC_HELP') ?></span>
<span class="txtWhatCvc"><h4><?php echo Mage::helper('skrill')->__('FRONTEND_CC_CVCHELP') ?></h4></span>
<span class="txtCards"><?php echo Mage::helper('skrill')->__('FRONTEND_CC_BRANDS') ?></span>
<span class="txtThreeDigits"><?php echo Mage::helper('skrill')->__('FRONTEND_TT_CVCWHERE') ?></span>
<a class="btnCustom btnCustomCancel" href="<?php echo $this->getBaseUrl()?>checkout/onepage"><?php echo Mage::helper('skrill')->__('FRONTEND_BT_CANCEL') ?></a>
<input type="submit" value="<?php echo Mage::helper('skrill')->__('FRONTEND_BT_CONFIRM') ?>" class="btnCustom btnCustomSubmit">
