<?php if ($this->isPossibleOnepageCheckout()):?>

<form id="my-custom-form" method='post' action="<?php echo $this->getCheckoutUrl(); ?>">
<?php if(Mage::helper('recurringandrentalpayments')->displayTermsandConditions())
	   {  ?>
		<button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" onclick="isradioselected();" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?>><span><span><?php echo $this->__('Proceed to Checkout') ?></span></span></button>
	<?php }
	 else 
	 {?>
		<button type="submit" title="<?php echo $this->__('Proceed to Checkout') ?>" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?>><span><span><?php echo $this->__('Proceed to Checkout') ?></span></span></button>
	
	 <?php } ?>  
</form>
<?php endif;  ?>


<script type="text/javascript">
    
	function isradioselected()
	{
		var ischeck = document.querySelector('input[name = "indies_recurringandrentalpayments_termsandconditions"]');
		if(ischeck.checked)
		{	
			document.getElementById("my-custom-form").submit();
		}
		else
		{
			document.getElementById('advice-indies_recurringandrentalpayments_termsandconditions').style.display = 'block';
		}
	}
</script>