<?php $alertHelper = Mage::helper('productalert');?>
<?php $this->setPreconfiguredValue(); ?>
<?php $_product = $this->getProduct(); ?>
<?php $_associatedProducts = $this->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<table class="data-table grouped-items-table" id="super-product-table">
    <col />
    <col />
    <col />
    <col />
    <col width="1" />
    <thead>
        <tr>
            <?php if ($this->getCanShowProductPrice($_product)): ?>
            <th class="a-center"><?php echo $this->__('Value') ?></th>
            <?php endif; ?>
            <th class="a-center"><?php echo $this->__('Points') ?></th>
            <?php //if ($_product->isSaleable()): ?>
            <th class="a-center"><?php echo $this->__('Qty') ?></th>
            <?php //endif; ?>
        </tr>
    </thead>
    <tbody>
    <?php if ($_hasAssociatedProducts): ?>
	<?php 
	$sortItems = array();
	foreach ($_associatedProducts as $_item){
		$sortItems[$_item->getFinalPrice()] = $_item;
	}
	ksort($sortItems);
	?>
    <?php foreach ($sortItems as $_item): ?>
        <?php $_finalPriceInclTax = $this->helper('tax')->getPrice($_item, $_item->getFinalPrice(), true) ?>
        <tr>
            <?php if ($this->getCanShowProductPrice($_product)): ?>
            <td class="a-center">
                <?php if ($this->getCanShowProductPrice($_item)): ?>
                <?php echo $this->getPriceHtml($_item, true) ?>
                <?php echo $this->getTierPriceHtml($_item) ?>
                <?php endif; ?>
            </td>
            <?php endif; ?>
			<td class="a-center">
				<p>
				<?php 
				  $_product = Mage::getModel('catalog/product')->load($_item->getId());
				  echo (int)$_product->getRewardpointsEarn();
				?>
				</p>
			</td>
            <?php //if ($_product->isSaleable()): ?>
            <td class="a-center">
            <?php if ($_item->isSaleable()) : ?>
                <div class="qty-holder">
                    <input type="text" name="super_group[<?php echo $_item->getId() ?>]" maxlength="12" value="<?php echo $_item->getQty()*1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
                    <div class="qty-changer">
                        <a href="javascript:void(0)" class="qty_inc"><i class="icon-up-dir"></i></a>
                        <a href="javascript:void(0)" class="qty_dec"><i class="icon-down-dir"></i></a>
                    </div>
                </div>
            <?php else: ?>
                
				<?php if($alertHelper->isStockAlertAllowed()):?>
				<?php 
				$url =  $this->getUrl('productalert/add/stock', array('product_id'    => $_item->getId(), Mage_Core_Controller_Front_Action::PARAM_NAME_URL_ENCODED => $alertHelper->getEncodedUrl()));
				?>
				<a href="<?php echo $this->escapeHtml($url) ?>" title="<?php echo $this->escapeHtml($url); ?>"><?php echo $this->__('Notify Me When In Stock'); ?></a>
				<?php else:?>
					<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
				<?php endif; ?>	
            <?php endif; ?>
            </td>
            <?php //endif; ?>
        </tr>
    <?php endforeach; ?>
    <?php else: ?>
       <tr>
           <td colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>"><?php echo $this->__('No options of this product are available.') ?></td>
       </tr>
    <?php endif; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('super-product-table')</script>
<?php echo $this->getChildHtml('product_type_data_extra') ?>
<style>
.alert-stock {display:none;}
</style>