<div class="box-account box-info box-truwallet-summary">
    <div class="box-head">
        <h2><?php echo $this->__('truWallet Information') ?></h2>
    </div>
    <div class="info-summary">
        <p><strong>
                <?php echo $this->__('Your truWallet balance is') ?>
                <strong class="truwallet-money"><?php echo $this->getTruWalletCredit() ?></strong>
                <img src="<?php echo $this->getSkinUrl('images/truwallet/truwallet.png') ?>" alt="truWallet"
                     style="display: inline-block;">
            </strong>
            <br/>
        </p>

        <p><strong class="truwallet-money">
                <a href="<?php echo $this->getUrl('truwallet/index/index') ?>"
                   title="<?php echo $this->__('View My truWallet') ?>">
                    <?php echo $this->__('View My truWallet') ?>
                </a>
            </strong></p>
    </div>
</div>
