
<?php

$customer_id = Mage::getSingleton('customer/session')->getCustomerId();
function randomKey($length) {
    $pool = array_merge(range(0,9), range('a', 'z'));

    for($i=0; $i < $length; $i++) {
        $key .= $pool[mt_rand(0, count($pool) - 1)];
    }
    return $key;
}
$random_num =  randomKey(5);
$mix_number = $customer_id.randomKey(5);
$link = 'http://travel.trunited.com/sale/7844-fall_into_savings_sale?refclickid='.$mix_number;
?>


  <?php 
    if(!Mage::getSingleton('customer/session')->isLoggedIn()){ ?>
<a href="<?php echo Mage::getUrl('customer/account/login'); ?>" title="Log In" class="ajaxlogin-login">Shop NOW</a>
    <?php }  
	 else{ ?>
        <a href='<?php echo $link ?>'>Shop now</a>
    <?php } ?>