<?php $state = Mage::app()->getRequest()->getRequestedRouteName(); ?>
<?php $_code = 'truwallet'; ?>
<?php

?>

<?php if (Mage::helper('truwallet')->isEnable()): ?>
    <dl id="<?php echo $_code ?>_container">
        <?php if (Mage::helper('customer')->isLoggedIn()): ?>
            <dt class="<?php echo $_code ?>">
                <input type="checkbox" style="display:none" name="payment[<?php echo $_code ?>]"
                       id="<?php echo $_code . "check" ?>"
                       onclick="changeUseCustomercredit(this, '<?php echo $this->getUrl('truwallet/index/checkCredit') ?>');"
                       checked="checked"/>

                <label for="<?php echo $_code ?>"
                       style="font-weight: bold; color: #666;display:inline;float:none;padding-left:10px">
                    <?php echo $this->__('Use truWallet balance to check out  (') ?>
                    <b id="truwallet_balance"> <?php echo $this->getAvaiableCustomerCreditLabel() ?> </b> <?php echo $this->__(" available )"); ?>
                </label>
            <form action="" method="post" onsubmit="return false;" id="truwallet-payment-form">
                <div id="cc_checkout">
                    <div class="checkout-credit-use">
                            <span style="float:left;margin-right: 5px;"><strong
                                    style="margin-left: 7px;"> <?php echo $this->__('You\'re using:') ?></strong></span>
                            <span style="float: left"
                                  id="checkout-cc-input"><strong><?php echo $this->getCurrentCreditAmountLabel(); ?></strong></span>

                        <div style="display: none"
                             class="checkout_cc_input_alert" id="checkout_cc_input_alert">
                            <input type="text" id="checkout_cc_inputtext"
                                   onchange="validateCheckOutCC(<?php echo $this->getCustomerCredit() ?>);"
                                   class="input-text validate-number validate-zero-or-greater required-entry form-control"
                                   value="<?php echo $this->getCreditUsed(); ?>"/>

                            <div class="validation-advice" style="display:none"
                                 id="advice-validate-number-checkout_cc_smaller"><?php echo $this->__('Please enter a number smaller than %s.', $this->getCustomerCreditLabel()); ?></div>
                        </div>
                        <img id="truwallet_cc_success_img" style=" display: none;float: left;margin-right: 4px;"
                             src="<?php echo $this->getSkinUrl('images/truwallet/i_msg-success.gif') ?>"/>

                        <div id="loading-credit" style="display: none;float: left; margin-left: 7px;margin-top: 12px;">
                            <p id="truwallet_cc_show_loading">
                                <img src="<?php echo $this->getSkinUrl('images/truwallet/opc-ajax-loader.gif') ?>"/>
                                <?php echo $this->__('Loading...') ?>
                            </p>
                        </div>
                        <?php if(Mage::helper('truwallet')->getEnableChangeBalance()){?>
                            <span class="edit-credit" id="checkout-cc-img"><img
                                    style="cursor: pointer;height: 15px;width: 15px;margin-left: 3px;"
                                    onclick="showEditText(this);"
                                    src="<?php echo $this->getSkinUrl('images/truwallet/btn_edit.gif'); ?>"></span>
                        <?php }?>
                        <?php
                        $moduleOnestepActive = Mage::getConfig()->getModuleConfig('Magestore_Onestepcheckout')->is('active', 'true');
                        ?>
                        <div class="buttons btn-truwallet">
                            <?php
                            if ($moduleOnestepActive && Mage::getStoreConfig('onestepcheckout/general/active') == '1') {
                                ?>
                                <button type="submit" class="button" id="checkout-cc-button" style="display: none;"
                                        onclick="updateCustomerCredit('<?php echo $this->getUpdateUrl(); ?>', '<?php echo $this->getCustomerCredit() ?>' , '<?php echo $state ?>' );">
                                    <span><span><?php echo Mage::helper('truwallet')->__('Apply') ?></span></span>
                                </button>

                                <button type="button" class="button" id="checkout-cc-button-cancel"
                                        style="display: none;"
                                        onclick="updateCustomerCredit('<?php echo $this->getUpdateUrl(); ?>', 0 , '<?php echo $state ?>' );">
                                    <span><span><?php echo Mage::helper('truwallet')->__('Cancel') ?></span></span>
                                </button>
                            <?php } else { ?>
                                <button type="submit" class="button" id="checkout-cc-button" style="display: none;"
                                        onclick="updateCustomerCredit('<?php echo $this->getUpdateUrl(); ?>','<?php echo $this->getCustomerCredit() ?>', '<?php echo $state ?>');">
                                    <span><span><?php echo Mage::helper('truwallet')->__('Apply') ?></span></span>
                                </button>
                                <button type="button" class="button" id="checkout-cc-button-cancel"
                                        style="display: none;"
                                        onclick="updateCustomerCredit('<?php echo $this->getUpdateUrl(); ?>', 0, '<?php echo $state ?>');">
                                    <span><span><?php echo Mage::helper('truwallet')->__('Cancel') ?></span></span>
                                </button>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </form>
        <?php else: ?>
            <div>
                <div class="checkout-cart-credit-amount">
                    <p>
                        <?php echo $this->__('Please ') . "<a href=\"" . $this->getUrl('customer/account/login') . "\">" . $this->__('login') . "</a>" . $this->__(' to use customer credit.'); ?>
                    </p>
                </div>
            </div>
        <?php endif ?>
        <script type="text/javascript">
            var ccPaymentForm = new VarienForm('truwallet-payment-form', true);
            $j = jQuery.noConflict();
            $j(document).ready(function(){
                <?php if($this->getCurrentCreditAmount() == 0 && $this->isReloadAutomatically()){?>
                updateCustomerCredit('<?php echo $this->getUpdateUrl(); ?>', '<?php echo $this->getCustomerCredit() ?>' , '<?php echo $state ?>' );
                <?php }?>
            });
        </script>
        </dt>
    </dl>
<?php endif ?>

