<?php
$state = Mage::app()->getRequest()->getRequestedRouteName();
$_code = 'truwallet';
?>
<?php if (Mage::helper('truwallet')->isEnable() && !Mage::helper('custompromotions')->truWalletInCart() && !Mage::helper('custompromotions')->truGiftCardInCart()): ?>
    <dl id="<?php echo $_code ?>_container">
        <?php if (Mage::helper('customer')->isLoggedIn()): ?>
            <dt class="<?php echo $_code ?>">
                <input type="checkbox" style="display:none" name="payment[<?php echo $_code ?>]"
                       id="<?php echo $_code . "check" ?>"
                       onclick="changeUseCustomercredit(this, '<?php echo $this->getUrl('truwallet/index/checkCredit') ?>');"
                       checked="checked"/>

                <!--<span style="padding-left:10px">
                    <?php /*echo $this->getLabelCurrent() */?>:
                    <b id="truwallet_balance"> <?php /*echo $this->getAvaiableCustomerCreditLabel() */?> </b>
                </span>
                <form action="" method="post" onsubmit="return false;" id="truwallet-payment-form">
                    <div class="checkout-credit-use">
                        <span style="margin-right: 5px;">
                            <strong style="margin-left: 7px;"> <?php /*echo $this->getLabelApplied() */?>: </strong>
                        </span>
                        <span id="checkout-cc-input"><?php /*echo Mage::helper('core')->currency($this->getCurrentCreditAmountLabel(), true, false); */?></span>

                    </div>
                </form>-->

                <input type="text" id="checkout_cc_inputtext" style="display: none;"
                       onchange="validateCheckOutCC(<?php echo $this->getCustomerCredit() ?>);"
                       class="input-text validate-number validate-zero-or-greater required-entry form-control"
                       value="<?php echo $this->getCreditUsed(); ?>"/>
                <div class="<?php echo $_code ?>_wrapper">
                    <div class="truwallet-img">
                        <img src="<?php echo $this->getSkinUrl('images/onestepcheckout/flatnew/truwallet.png');?>" title="<?php echo $this->__('TruWallet Balance')?>" />
                        <span class="current_balance"><?php echo $this->getAvaiableCustomerCreditLabel() ?></span>
                        <span class="current_balance_text"><?php echo $this->__('Current TruWallet Balance') ?></span>
                    </div>
                    <div class="used">
                        <span><?php echo $this->getLabelApplied();?> : <?php echo Mage::helper('core')->currency($this->getCurrentCreditAmountLabel(), true, false);?></span>
                    </div>
                </div>
        <?php else: ?>
            <div>
                <div class="checkout-cart-credit-amount">
                    <p>
                        <?php echo $this->__('Please ') . "<a href=\"" . $this->getUrl('customer/account/login') . "\">" . $this->__('login') . "</a>" . $this->__(' to use customer credit.'); ?>
                    </p>
                </div>
            </div>
        <?php endif ?>
        <script type="text/javascript">
            var ccPaymentForm = new VarienForm('truwallet-payment-form', true);
            $j = jQuery.noConflict();
            $j(document).ready(function () {
                <?php if($this->getCurrentCreditAmount() == 0 && $this->isReloadAutomatically() && !Mage::helper('custompromotions')->truWalletInCart() && !Mage::helper('custompromotions')->truGiftCardInCart()){?>
                updateCustomerCredit(
                    '<?php echo $this->getUpdateUrl(); ?>',
                    '<?php if(Mage::helper('custompromotions')->truWalletInCart() || Mage::helper('custompromotions')->truGiftCardInCart()) echo '0'; else echo $this->getCustomerCredit() ?>',
                    '<?php echo $state ?>'
                );
                <?php } else if((Mage::helper('custompromotions')->truWalletInCart() || Mage::helper('custompromotions')->truGiftCardInCart()) && $this->isReloadAutomatically()){?>
                updateCustomerCredit(
                    '<?php echo $this->getUpdateUrl(); ?>',
                    '0',
                    '<?php echo $state ?>'
                );
                <?php }?>
            });
        </script>
        <style type="text/css">
            #onestepcheckout-trunited-discounts #truwallet_container .truwallet {
                background-color: # <?php echo $this->getBackgroundColor()?>;
                color: # <?php echo $this->getTextColor()?>;
                border: 1px solid # <?php echo $this->getBackgroundColor()?>;
            }
        </style>
        </dt>
    </dl>
<?php endif; ?>

