<?php if($this->getSource() instanceof Mage_Sales_Model_Order){ ?>
<?php if ((float) $this->getSource()->getRecurringDiscountAmountRefunded()): ?>
    <tr>
        <td class="label"><strong><?php echo 'Recurring Discount refunded to customer' ?></strong></td>
        <td><strong><?php echo $this->getSource()->getRecurringDiscountAmountRefunded(); ?></strong></td>
    </tr>
<?php endif; ?>
<?php } else { ?>
<?php if ((float) $this->getSource()->getRecurringDiscountAmount()): ?>
    <tr>
        <td class="label"><strong><?php echo 'Recurring Discount Refunded' ?></strong></td>
        <td><strong><?php echo $this->displayPrices($this->getSource()->getBaseRecurringDiscountAmount(),$this->getSource()->getRecurringDiscountAmount()); ?></strong></td>
    </tr>
<?php endif; 
}?>

