<?php $this->setPriceDataObject($this->getSource()) ?>
<?php if ((float) $this->getSource()->getRecurringDiscountAmount()): ?>
    <tr>
       
    	<?php if(($this->getSource()->getRecurringDiscountAmount() != 0)): ?>
        
	        <td class="label">
				<?php echo 'Recurring Discount'; ?>
			</td>
    	    <td>
        	    <?php echo $this->displayPrices($this->getSource()->getBaseRecurringDiscountAmount(), $this->getSource()->getRecurringDiscountAmount()); ?>
        	</td>
        <?php endif; ?>
    </tr>
<?php endif; ?>