<?php $menuHelper = Mage::helper('megamenu'); ?>
<?php $menuData = $menuHelper->getMenuData(); extract($menuData); ?>
 <div class="collapse navbar-collapse" id="main-menu">
        <ul class="nav navbar-nav navbar-right nav-right">
          <?php echo $menuHelper->getMenuContent(); ?>
          <?php if(Mage::getSingleton('customer/session')->isLoggedIn()){ 
                //not logged in
                    echo "<li><a href=\"/customer/account/\">My Account</a></li>";
                } 
            ?>
          <li class="sign-in-link">
          <?php if(!Mage::getSingleton('customer/session')->isLoggedIn()){ 
                //not logged in
                echo "<a href=\"/customer/account/login/\">Sign In</a></li>";
                
            }else{ 
                // logged in
                echo "<a href=\"/customer/account/logout\">Sign Out</a>";
            } ?> 
          <li class="cart-wrapper hidden-xs">
<!--
            <a href="#" class="desktop-cart-link">
              Cart
              <div class="desktop-cart">
                <div class="itmes-count"><?php //echo $_cartQty ?></div>
              </div>
            </a>
-->
          </li>
        </ul>        
</div>