<?php
$category = Mage::registry('current_category');
$subcategoryIds = $category->getChildren();
$subcategoryIds = explode(",", $subcategoryIds);
$todayStartOfDayDate  = Mage::app()->getLocale()->date()
        ->setTime('00:00:00')
        ->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);

$todayEndOfDayDate  = Mage::app()->getLocale()->date()
        ->setTime('23:59:59')
        ->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);
$_productCollection = $this->getLoadedProductCollection();
$_productCollection->clear()->addAttributeToFilter('news_from_date', array('or'=> array(
            0 => array('date' => true, 'to' => $todayEndOfDayDate),
            1 => array('is' => new Zend_Db_Expr('null')))
        ), 'left')
        ->addAttributeToFilter('news_to_date', array('or'=> array(
            0 => array('date' => true, 'from' => $todayStartOfDayDate),
            1 => array('is' => new Zend_Db_Expr('null')))
        ), 'left')->setPageSize(150)->load();
$_helper = $this->helper('catalog/output');
$_image_helper = $this->helper('catalog/image');
$store = Mage::app()->getStore();
$code = $store->getCode();
$is_logged = Mage::getSingleton('customer/session')->isLoggedIn();
$login_url = Mage::helper('customproduct')->getLoginUrl();

$aspect_ratio = $this->getData("aspect_ratio");
if ($aspect_ratio == null) {
    $aspect_ratio = Mage::getStoreConfig("porto_settings/category/aspect_ratio", $code);
}
$ratio_width = $this->getData("image_width");
if (!$ratio_width) {
    $ratio_width = Mage::getStoreConfig("porto_settings/category/ratio_width", $code);
}
$ratio_height = $this->getData("image_height");
if (!$ratio_height) {
    $ratio_height = Mage::getStoreConfig("porto_settings/category/ratio_height", $code);
}

if (!$ratio_width)
    $ratio_width = 300;
if (!$ratio_height)
    $ratio_height = 400;
?>
    <style type="text/css">
        a.addtocart{
            font-size: 13px!important;
            color: #ffffff!important;
            height: 43px!important;
            width: 154px!important;
            background: #00b5cb!important;
            text-align: center!important;
            display: inline-block!important;
            text-transform: uppercase!important;
            border-radius: 35px!important;
            text-decoration: none!important;
            padding-top: 5px!important;
            -webkit-transition: all .3s !important;
            -o-transition: all .3s !important;
            transition: all .3s!important;
        }
        a.addtocart:hover{
            border: 0px!important;
            background: #ec7b42 !important;
        }
    </style>
<?php
$_coreHelper = $this->helper('core');
?>
<?php if ($_coreHelper->isModuleEnabled("Magegiant_Dailydeal")): ?>
    <script type="text/javascript">
        //<![CDATA[
        var dailydealTimeCountersCategory = new Array();
        var i = 0;
        //]]>
    </script>
<?php endif; ?>
<?php if (!$_productCollection->count()): ?>
    <div class="category-products">
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    </div>
<?php else: ?>
    <div class="category-products">
    <?php 
    foreach($subcategoryIds as $cat_id):
    $cat = Mage::getModel('catalog/category')->load($cat_id);
    $cat_name = strtoupper($cat->getName());
    ?>
    <div class="search_bar text-center padd_bot">
        <h3 class="pad_last"><?php echo $cat_name; ?></h3>
        <div class="clearfix"></div>
    </div>
        <?php // List mode ?>
        <?php if ($this->getMode() == 'grid'): ?>
        <?php // Grid Mode ?>
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = Mage::getStoreConfig("porto_settings/category_grid/columns", $code); ?>
            <div class="product_blk no_load_more">
                <ul>
                <?php $i = 0; $flag_shop_now = false;
                foreach ($_productCollection as $_product): ?>
                    <?php if(!in_array($cat_id,$_product->getCategoryIds())) continue; ?>
                    <?php $product = $_product;?>
                    <li class="col-sm-3 col-xs-4">
                        <div class="product">
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                     src="<?php if ($aspect_ratio): ?><?php echo $_image_helper->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width); ?><?php else: ?><?php echo $_image_helper->init($_product, 'small_image')->resize($ratio_width, $ratio_height); ?><?php endif; ?>"
                                     width="<?php echo $ratio_width; ?>"
                                     <?php if (!$aspect_ratio): ?>height="<?php echo $ratio_height; ?>"<?php endif; ?>
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                            <h5> 
                                <?php
                                if(Mage::helper('customproduct')->isAppliedToProductType($_product->getTypeId())){
                                    $shop_now_url = Mage::helper('customproduct')->getShopNowUrl($_product);

                                }?>
                                <a href="<?php echo $_product->getProductUrl() ?>"
                                    title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                              
                            </h5>
                            <div class="clearfix"></div>
                            <a href="<?php echo $_product->getProductUrl() ?>" class="view_details" rel="nofollow" class="addtocart custom-url">
                                <span><?php echo $this->__('View Details');?></span>
                            </a>
                        </div>
                    </li>
                <?php endforeach ?>
                </ul>
            </div>
        <?php endif; ?>
        <?php if (Mage::getStoreConfig("ajax_catalog/price_slider_settings/infinitescroll", $code)): ?>
            <div class="infinite-loader"><span class="loading"><i
                            class="ajax-loader small animate-spin"></i><?php echo $this->__("Loading ..."); ?></span><a
                        href="javascript:void(0)" class="btn-load-more"><?php echo $this->__("Load More ..."); ?></a>
            </div>
        <?php endif; ?>
    <?php endforeach ; ?>
    </div>
<?php endif; ?>