<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2014 Skrill
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle())." ".Mage::helper('skrill')->__('BACKEND_TT_BY_PAYON'); ?>
<br />
<?php 
	$ip_country = $this->getInfo()->getAdditionalInformation('skrill_ip_country');
	if ( $ip_country )
		echo Mage::helper('skrill')->__('SKRILL_BACKEND_ORDER_ORIGIN')." : ".Mage::app()->getLocale()->getCountryTranslation($ip_country)."<br />";
?>
<?php 
	$status = $this->getInfo()->getAdditionalInformation('skrill_status');
	$payment_type = $this->getInfo()->getAdditionalInformation('skrill_transaction_code');
	$payment_brand = $this->getInfo()->getAdditionalInformation('skrill_payment_brand');
	$bin = $this->getInfo()->getAdditionalInformation('skrill_bin');

	$separator_type = 'info';
    $comment = Mage::helper('skrill')->getPayonComment($status, $payment_type, $payment_brand, $bin, $separator_type);
	echo $comment;
?>
