<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<!--    <link rel="stylesheet" href="/resources/demos/style.css">-->
    <style type="text/css">
        #project-label {
            display: block;
            font-weight: bold;
            margin-bottom: 1em;
        }

        .form-list .input-box label{
            padding-top: 5px;
            font-size: 12px;
            font-style: italic;
        }
    </style>
</head>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<?php $names = $this->getAffiliateName(); ?>

<div class="fieldset">
    <h2 class="legend"><?php echo $this->__('Affiliate Referral Information') ?></h2>

    <ul class="form-list">
        <li class="fields">
            <div class="field">
                <label for="affiliate_name" class=""><?php echo $this->__('Who Referred Me:') ?></label>

                <div class="input-box who_refers_me">
                    <?php
                    $accountInfo = Mage::helper('affiliateplus/account')->getAffiliateInfoFromCookie();
                    $email_refer = Mage::getSingleton('core/session')->getEmailRefer();
                    $affiliate_account = null;
                    if ($email_refer != null) {
                        $customer_refer = Mage::getModel("customer/customer");
                        $customer_refer->setWebsiteId(Mage::app()->getStore()->getWebsiteId());
                        $customer_refer->loadByEmail($email_refer);
                        if ($customer_refer->getId()) {
                            $affiliate_account = Mage::getModel('affiliateplus/account')->loadByCustomerId($customer_refer->getId());
                        }
                    }

                    $default_name = '';
                    $default_id = '';
                    if ($accountInfo) {
                        $default_name = $accountInfo->getName();
                        $default_id = $accountInfo->getId();
                    } else if ($affiliate_account != null && $affiliate_account->getId()) {
                        $default_name = $affiliate_account->getName();
                        $default_id = $affiliate_account->getId();
                    }
                    ?>
                    <input type="text" name="affiliate_name" id="affiliate_name"
                           placeholder="<?php echo $this->__('Enter Affiliate Name'); ?>"
                           onchange="checkAffiliateCouponCodeExisting('<?php echo $this->getUrl('affiliateplus/account/checkAffiliateName') ?>', this)"
                           value="<?php echo $default_name ?>" title="<?php echo $this->__('Affiliate Name') ?>"
                           class="input-text wrm"/>

                    <br/><label for="affiliate_name"
                                class=""><?php echo $this->__('Please enter the mobile # of the person who referred you and type at least 7 characters') ?></label>

                    <div id="refers_error"
                         class="error_refers_me"><?php echo $this->__('You must select an Affiliate or check the box ‘no one referred me'); ?></div>
                    <div id="refers_mobile_error"
                         class="error_refers_me"><?php echo $this->__('Please enter a valid phone number. For example (123) 456-7890 or 123-456-7890.'); ?></div>
                    <input type="hidden" id="affiliate_id" name="affiliate_id" value="<?php echo $default_id ?>">
                    <button class="close-icon" type="button" onclick="hideClose(this);">
                </div>
                <span id="affiliate-please-wait-email" style="display:none;" class="opc-please-wait">
                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/> &nbsp; <?php echo $this->__('Checking coupon code') ?>
                    ...
                </span>

                <div id="affiliate_message_hidden_email" class="affiliate_message"></div>
                <?php //if (!$accountInfo): ?>
                <input style="float: left" type="checkbox" class="checkbox" name="no_refers_me" id="no_refers_me"
                       value="1" onclick="checkNoRefer()"/>
                <label for="no_refers_me"><?php echo $this->__('No one referred me.') ?></label>
                <?php //endif; ?>
            </div>
        </li>
    </ul>
</div>

<script type="text/javascript" scr="<?php echo $this->getSkinUrl('js/magestore/customize.js');?>"></script>
