<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <style>
        #project-label {
            display: block;
            font-weight: bold;
            margin-bottom: 1em;
        }
    </style>
</head>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<?php $names = $this->getAffiliateName(); ?>
<script>
    var $jq = jQuery.noConflict();
    $jq(function () {
        $jq("#affiliate_name").keydown(function (e) {
            var checklength = $jq('#affiliate_name').val().length;

            if (checklength >= 2) {
                var projects = <?php echo $names; ?>;
                $jq("#affiliate_name").autocomplete({
                    minLength: 3,
                    source: projects,
                    focus: function (event, ui) {
                        $jq("#affiliate_name").val(ui.item.label);
                        return false;
                    },
                    select: function (event, ui) {
                        $jq("#affiliate_name").val(ui.item.label);
                        $jq("#affiliate_id").val(ui.item.value);
                        $jq("#affiliate_message_hidden_email").hide();
                        $jq('#no_refers_me').attr('checked', false);
                        return false;
                    }
                })
            }
        });
    });

</script>
<div class="fieldset">
    <h2 class="legend"><?php echo $this->__('Affiliate Referral Information') ?></h2>

    <div
        class="error_refers_me"><?php echo $this->__('You must select an Affiliate Name or check the box ‘no one referred me'); ?></div>
    <ul class="form-list">
        <li class="fields">
            <div class="field">
                <label for="affiliate_name" class=""><?php echo $this->__('Who Referred Me:') ?></label>

                <div class="input-box who_refers_me">
                    <?php
                    $accountInfo = Mage::helper('affiliateplus/account')->getAffiliateInfoFromCookie();
                    $email_refer = Mage::getSingleton('core/session')->getEmailRefer();
                    $affiliate_account = null;
                    if ($email_refer != null) {
                        $customer_refer = Mage::getModel("customer/customer");
                        $customer_refer->setWebsiteId(Mage::app()->getStore()->getWebsiteId());
                        $customer_refer->loadByEmail($email_refer);
                        if ($customer_refer->getId()) {
                            $affiliate_account = Mage::getModel('affiliateplus/account')->loadByCustomerId($customer_refer->getId());
                        }

                    }

                    $default_name = '';
                    $default_id = '';
                    if ($accountInfo) {
                        $default_name = $accountInfo->getName();
                        $default_id = $accountInfo->getId();
                    } else if ($affiliate_account != null && $affiliate_account->getId()) {
                        $default_name = $affiliate_account->getName();
                        $default_id = $affiliate_account->getId();
                    }
                    ?>
                    <input type="text" name="affiliate_name" id="affiliate_name"
                           placeholder="<?php echo $this->__('Enter Affiliate Name'); ?>"
                           onchange="checkAffiliateCouponCodeExisting('<?php echo $this->getUrl('affiliateplus/account/checkAffiliateName') ?>', this)"
                           value="<?php echo $default_name ?>" title="<?php echo $this->__('Affiliate Name') ?>"
                           class="input-text wrm"/>
                    <br/><label for="affiliate_name"
                                class=""><?php echo $this->__('Please type at least 3 characters') ?></label>
                    <input type="hidden" id="affiliate_id" name="affiliate_id" value="<?php echo $default_id ?>">
                    <button class="close-icon" type="button" onclick="hideClose(this);">
                </div>
                <span id="affiliate-please-wait-email" style="display:none;" class="opc-please-wait">
                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/> &nbsp; <?php echo $this->__('Checking coupon code') ?>
                    ...
                </span>

                <div id="affiliate_message_hidden_email" class="affiliate_message"></div>
                <?php //if (!$accountInfo): ?>
                <input style="float: left" type="checkbox" class="checkbox" name="no_refers_me" id="no_refers_me"
                       value="1" onclick="checkNoRefer()"/>
                <label for="no_refers_me"><?php echo $this->__('No one referred me.') ?></label>
                <?php //endif; ?>
            </div>
        </li>
    </ul>
</div>
<script type="text/javascript">
    $j = jQuery.noConflict();
    if ($j('.wrm').val() == '') {
        $j('.close-icon').css({display: "none"});
    }

    $j(".wrm").on("input", function (e) {
        var value = $j(this).val();
        if ($j(this).data("lastval") != value) {
            $j(this).data("lastval", value);
        }

        if (value == '') {
            $j('.close-icon').css({display: "none"});
        } else {
            $j('.close-icon').css({display: "inline-block"});
        }
    });

    $j('.close-icon').click(function () {
        $j('.close-icon').hide();
        $('affiliate_name').value = '';
        $('affiliate_id').value = '';
    });

    function hideClose(el){
        $j(el).hide();
        $('affiliate_name').value = '';
        $('affiliate_id').value = '';
    }

    $j('#form-validate').submit(function () {
        var affiliate_name = $('affiliate_name').value;
        var no_refers_me = $('no_refers_me').checked;
        if (affiliate_name == '' && no_refers_me === false) {
            $j('.error_refers_me').slideDown().delay(3000).slideUp();
            // $j('#form-validate').find('button[type="submit"]').prop('disabled',true);
            return false;
        }

    });
    function checkAffiliateCouponCodeExisting(requestUrl, el) {
        var affiliate_name = $('affiliate_name').value;
        var affiliate_id = $('affiliate_id').value;
        var no_refers_me = $('no_refers_me').checked;

        var params = {affiliate_name: affiliate_name, affiliate_id: affiliate_id};
        $('affiliate-please-wait-email').show();
        $('affiliate_message_hidden_email').hide();


        $j('#form-validate').find('button[type="submit"]').prop('disabled', true);
        new Ajax.Updater(
            'affiliate_message_hidden_email',
            requestUrl,
            {
                method: 'get',
                onComplete: function () {
                    endCheckEmailRegister();
                    if (affiliate_name == '' && no_refers_me === false)
                        $j('.error_refers_me').show();
                    else
                        $j('#form-validate').find('button[type="submit"]').removeProp('disabled');
                },
                onSuccess: '',
                onFailure: '',
                parameters: params,
                postBody: params
            }
        );

    }

    function endCheckEmailRegister() {
        $('affiliate-please-wait-email').hide();
        $('affiliate_message_hidden_email').show();
        if ($('is_valid_email').value == '0') {
//            $('affiliate_name').value = '';
//            $('no_refers_me').checked=true;
        }
    }
    function checkNoRefer() {
        $('affiliate_name').value = '';
        $('affiliate_id').value = '';
        $j('.close-icon').hide();
        if ($('no_refers_me').checked == false) {
            $('affiliate_name').addClassName('required-entry');
        } else {
            $('affiliate_name').removeClassName('required-entry');
            $('affiliate_message_hidden_email').hide();
        }
    }
</script>
