
<div class="left_block">
    <div class="sidebar active">
        <h6><?php echo $this->__('Business Tool');?></h6>
        <div class="sub_blk">
            <ul>
                <?php $_links = $this->getLinks() ?>
                <?php foreach ($_links as $_link): ?>
                    <?php if ($this->isActive($_link)): ?>
                        <li><a href="<?php echo $_link->getUrl() ?>">
                                <small><img src="<?php echo $this->getSkinUrl('images/icon39.png');?>" width="26" height="26" alt="icon"></small>
                                <span><?php echo $_link->getLabel() ?></span>
                            </a>
                        </li>
                    <?php else: ?>
                        <li>
                            <a href="<?php echo $_link->getUrl() ?>">
                                <small><img src="<?php echo $this->getSkinUrl('images/icon35.png');?>" width="26" height="26" alt="icon"></small>
                                <span><?php echo $_link->getLabel() ?></span>
                            </a>
                        </li>
                    <?php endif ?>
                <?php endforeach ?>
            </ul>
        </div>
    </div>
</div>
<script type="text/javascript">
    $j = jQuery.noConflict();
    $j(document).ready(function(e) {
        $j(".sidebar.active .sub_blk").show();
        $j(".sidebar h6").click(function() {
            $j(this).parent().toggleClass('active');
            $j(this).parent().siblings().removeClass('active');
            $j(this).parent().find('.sub_blk').slideToggle();
            $j(this).parent().siblings().find('.sub_blk').slideUp();
        });

        $j(window).scroll(function () {
            if ($j(this).scrollTop() > 100) {
                $j('.BaclToTop').fadeIn();
            } else {
                $j('.BaclToTop').fadeOut();
            }
        });

    } );
</script>
