<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo $this->__('My TruBox') ?></span></strong>
    </div>
    <div class="block-content">
        <ul id="trubox-navigation-<?php echo $this->getNameInLayout() ?>">
            <?php $_links = $this->getLinks() ?>
            <?php foreach ($_links as $_link): ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current"><strong><?php echo $_link->getLabel() ?></strong></li>
                <?php else: ?>
                    <li>
                        <a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a>
                    </li>
                <?php endif ?>
            <?php endforeach ?>
        </ul>

        <br /><br />
        <div><strong><?php echo $this->__('TRUBOX CATEGORIES');?></strong></div>
        <br />
        <ul id="trubox-navigation-category-<?php echo $this->getNameInLayout() ?>">
            <?php $categories = $this->getCategories(); ?>
            <?php foreach ($categories as $category): ?>
                <li>
                    <a href="<?php echo $this->getCategoryLink($category->getId()); ?>"><?php echo $category->getName(); ?></a>
                </li>
            <?php endforeach ?>
        </ul>
        <script type="text/javascript">
            decorateGeneric($('trubox-navigation-<?php echo $this->getNameInLayout() ?>').childElements(),['last']);
            decorateGeneric($('trubox-navigation-category-<?php echo $this->getNameInLayout() ?>').childElements(),['last']);
        </script>
    </div>
</div>
