<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Eventdiscount
 * @version    1.0.5
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
$_element = $this->getElement();

$_note = $_element->getNote();
$_trId = $_element->getHtmlContainerId();
$_class = $_element->getFieldsetHtmlClass();
$elemId = 'rule_position';
?>

<?php
if (Mage::app()->getRequest()->getControllerName() == 'admin_timer') {
    $attributeName = "attributes[{$this->getName()}]";
} else {
    $attributeName = $this->getName();
}
$attributeName = 'position';

?>
<?php if (!$_element->getNoDisplay()): ?>
<tr<?php if ($_trId): ?> id="<?php echo $_trId ?>"<?php endif; ?>>
    <?php if ($_element->getType() == 'hidden'): ?>
    <td colspan="2" class="hidden"><?php echo trim($_element->getElementHtml()) ?></td>
    <?php else: ?>
    <td class="label<?php echo $_class ? " {$_class}-label" : ''?>"><?php echo trim($_element->getLabelHtml()) ?></td>
    <td class="<?php echo $_element->hasValueClass() ? $_element->getValueClass() : 'value' ?><?php echo $_class ? " {$_class}-value" : ''?>">

        <div id="<?php echo $elemId; ?>_container" class="aw_eventdiscount_position_container">
            <input type="hidden" id="<?php echo $elemId; ?>_input" name="<?php echo $attributeName; ?>"
                   value="<?php echo $_element->getValue(); ?>">
            <input id="<?php echo $elemId; ?>" class="input-text" type="text" value=""
                   onfocus="focusNextInput($('<?php echo $this->getHtmlId(); ?>'))">

            <div id="<?php echo $elemId; ?>_button"
                 class="aw_eventdiscount_position_button"><?php echo $this->__('Click here to select'); ?></div>
            <div id="<?php echo $elemId; ?>_selectbox" class="aw_eventdiscount_selectbox">
                <?php foreach (array('T', 'M', 'B') as $V): ?>
                <?php foreach (array('L', 'C', 'R') as $H): ?>
                    <div id="<?php echo $elemId; ?>_<?php echo $V . $H; ?>" class="position_selector"></div>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </div>
        </div>
    </td>
    <?php endif; ?>
</tr>
<?php endif; ?>
<script type="text/javascript">
    awPosition.register($('<?php echo $elemId; ?>_container'), $('<?php echo $elemId; ?>_button'), $('<?php echo $elemId; ?>_input'), $('<?php echo $elemId; ?>_selectbox'));
    <?php foreach ($_element->getValues() as $option): ?>
    awPosition.addPosition('<?php echo $option['value']; ?>', '<?php echo $this->__($option['label']); ?>');
        <?php endforeach; ?>
    <?php foreach (array('T', 'M', 'B') as $V): ?>
        <?php foreach (array('L', 'C', 'R') as $H): ?>
        awPosition.registerSelector($('<?php echo $elemId; ?>_selectbox'), $('<?php echo $elemId; ?>_<?php echo $V . $H; ?>'), '<?php echo $V . $H; ?>', $('<?php echo $elemId; ?>_input'), $('<?php echo $elemId; ?>'));
            <?php endforeach; ?>
        <?php endforeach; ?>
    awPosition.setInputValue($('<?php echo $elemId; ?>_input'), $('<?php echo $elemId; ?>'), '<?php echo $_element->getValue(); ?>', $('<?php echo $elemId; ?>_selectbox'));
</script>