<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo $this->__('My truWallet') ?></span></strong>
    </div>
    <div class="block-content">
        <ul id="truwallet-navigation-<?php echo $this->getNameInLayout() ?>">
            <?php $_links = $this->getLinks() ?>
            <?php foreach ($_links as $_link): ?>
            	<?php if (!$_link->getEnable()  || (strpos(trim($_link->getLabel()), 'truWallet Money') > 0
                        && !Mage::helper('truwallet')->getEnableSharing() )) continue; ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current"><strong><?php echo $_link->getLabel() ?></strong></li>
                <?php else: ?>
                    <li>
                        <a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a>
                    </li>
                <?php endif ?>
            <?php endforeach ?>
        </ul>
        <script type="text/javascript">
        	decorateGeneric($('truwallet-navigation-<?php echo $this->getNameInLayout() ?>').childElements(),['last']);
        </script>
    </div>
</div>
