<?php
/**
 * Payments miniform request template
 */

$object_transfer = Mage::helper('affiliateplus/config')->getTransferConfig();
?>
<form id="affiliateplus_payment_request_miniform" action="<?php echo $this->getFormActionUrl() ?>" method="post">
    <div class="affiliateplus_form_request">
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 my-blance">
            <strong><?php echo $this->__('My Balance: ') ?></strong>
            <?php echo $this->getFormatedBalance() ?>
        </div>
        <?php if ($this->canRequest()): ?>
            <div class="input_fields_form form-inline request-amount-money col-lg-6 col-md-6 col-sm-12 col-xs-12 ">

                <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7 input-blance">
                    <input id="request_amount" name="amount" value="<?php echo $this->__('Request Amount') ?>"
                           class="input-text required-entry form-control input-text required-entry validate-greater-than-zero"
                           type="text" onchange="checkAmountBalance(this);" onfocus="if (this.value == this.defaultValue)
                                    this.value = '';" onblur="if (this.value == '') this.value = this.defaultValue;"
                           placeholder="<?php echo $this->__('Request Amount'); ?>"
                    />
                    <input type="hidden" id="from_request_page" name="from_request_page" value="1"/>
                </div>
                <div class="request-withrawal col-lg-5 col-md-5 col-sm-5 col-xs-5">
                    <button class="button button-config request-amount"
                            title="<?php echo $this->__('Request Withdrawal') ?>" type="submit">
                        <span><span><?php echo $this->__('Request Withdrawal') ?></span></span>
                    </button>
                </div>
            </div>
        <?php endif ?>
    </div>


</form>
<form id="affiliateplus_payment_transfer_miniform" action="<?php echo $this->getTransferFormActionUrl() ?>" method="post">
    <div class="affiliateplus_form_transfer affiliateplus_form_request">
        <div class="input_fields_form form-inline request-amount-money col-lg-6 col-lg-offset-6 col-md-6 col-md-offset-6 col-sm-12 col-xs-12 ">
            <div class="<?php if($object_transfer == 1){?>col-lg-7 col-md-7 col-sm-7 col-xs-7<?php } else if($object_transfer == 2) {?>col-lg-5 col-md-5 col-sm-5 col-xs-5 <?php }?> input-blance">
                <input id="transfer_amount" name="transfer_amount" value="<?php echo $this->__('Transfer Amount') ?>"
                       class="input-text required-entry form-control input-text required-entry validate-greater-than-zero"
                       type="text" onchange="checkAmountBalance(this);" onfocus="if (this.value == this.defaultValue)
                                    this.value = '';" onblur="if (this.value == '') this.value = this.defaultValue;"
                       placeholder="<?php echo $this->__('Transfer Amount'); ?>"
                />
                <input type="hidden" id="from_request_page" name="from_request_page" value="1"/>
            </div>

            <?php if($object_transfer == 1){?>
                <div class="request-withrawal col-lg-5 col-md-5 col-sm-5 col-xs-5">
                    <button class="button button-config request-amount"
                            title="<?php echo $this->__('Transfer to truWallet') ?>" type="submit">
                        <span><span><?php echo $this->__('Transfer to truWallet') ?></span></span>
                    </button>
                </div>
                <?php if(Mage::helper('truwallet')->getEnableTransferBonus()){?>
                <div class="bonus-message message">
                    <?php echo Mage::helper('truwallet')->getMessageTransferBonus();?>
                </div>
                <?php }?>
            <?php } else if($object_transfer == 2) {?>
                <div class="request-withrawal col-lg-7 col-md-7 col-sm-7 col-xs-7">
                    <button class="button button-config request-amount"
                            title="<?php echo $this->__('Transfer to TruGiftCard') ?>" type="submit">
                        <span><span><?php echo $this->__('Transfer to Trunited Gift Card') ?></span></span>
                    </button>
                </div>
                <?php if(Mage::helper('trugiftcard')->getEnableTransferBonus()){?>
                    <div class="bonus-message message">
                        <?php echo Mage::helper('trugiftcard')->getMessageTransferBonus();?>
                    </div>
                <?php }?>
            <?php }?>
        </div>
    </div>
</form>
<?php if ($this->canRequest()): ?>
    <script type="text/javascript">
        //<![CDATA[
        var affiliateplusPaymentRequestMiniform = new VarienForm('affiliateplus_payment_request_miniform', true);
        var affiliateplusPaymentTransferMiniform = new VarienForm('affiliateplus_payment_transfer_miniform', true);
        var request_amount_max = <?php echo $this->getMaxAmount() ?>;
        function checkAmountBalance(el) {
            el.value = parseFloat(el.value);
            if (el.value < 0)
                el.value = 0;
            else if (el.value > request_amount_max || el.value == 'NaN')
                el.value = request_amount_max;
        }
        //]]>
    </script>
    <div class="clear"></div>
    <?php
endif ?>
