<?php
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    // Get the customer object from customer session
    $customer = Mage::getSingleton('customer/session')->getCustomer();
    
    $custID = $customer->getID();//get customer id

}

?>

<div class="col-sm-12">
    <div id="left-blk" class="col-sm-4">
        <div class="block-left" style="text-align: center;">
            <div class="div-content">
                <ul>
                    <li>
                        <a href="#" alt="Discount School Supply" rel="nofollow" target="_blank">
                        <img src="https://www.ebates.com/image/store/icon/2946/icon-280x80.gif" width="225" height="48" class="lg-image">
                        </a>
                    </li>
                    <li class="cashbackwas">
                        was 1.0%
                    </li>
                    <li class="cashback">
                        <div>
                            <a href="#" rel="nofollow" target="_blank" class="cb nohover">2.0% Cash Back</a>
                        </div>
                    </li>
                    <li class="mar-5-b"><a href="#" rel="nofollow" target="_blank" class="button-shop-lg">Shop Now <span class="arrow arr-right"></span></a></li>
                </ul>
            </div>
        </div>
        <div class="block-left store-info">
            <h2 style="color:#333;">About Walmart Coupons, Deals and Cash Back</h2>
            <div>
                <p class="about-walmart">Walmart has become one of the largest and most popular discount department stores in the world, and with prices as low as they are, it&rsquo;s no wonder why. Walmart shoppers have come to expect the best deals on the largest selection of consumer goods through Walmart stores. With Walmart coupons, seasonal sales and a low-price guarantee, Walmart really does outdo other discount department stores time and time again. Walmart provides the largest selection of electronics, <br /></p>
            </div>
        </div>
        <div class="block-left store-info">
            <div class="expandablediv">
                <h2 class="shipping">Cash Back Terms</h2>
            </div>
            <div class="expandablediv">
                <p class="about-walmart">
                    <strong>Exclusions:</strong>                            Cash Back is not available on Apple Watch, newest model iPhones, Walmart Grocery to Go, cellular purchases, prepaid phone cards (Straight Talk), prescription drugs, travel, financial services, tires, Walmart Connect Internet Service, gift card/online gift cards and ShippingPass subscription.
                    <br/>                
                </p>
                <p class="about-walmart">
                    <strong>Special Terms:</strong> 								Cash Back is not available on orders deemed by Walmart to be for reselling purposes.
                </p>
            </div>
        </div>
        <div class="block-left store-info">
            <h2 class="shipping">Free Shipping</h2>
            <p>Walmart offers free shipping on orders of $50 or more.</p>
            <p><a href="#" target="_blank" class="cb">Shop Walmart with 2.0% Cash Back <span class="arrow-cb-sm arr-right"></span></a></p>
        </div>
    </div>
    <div  id="rightd-blk" class="col-sm-8">
        <div id="store-coupons" class="store-coupons">
            <div class="store-heading">
                <h2>Walmart Coupons, Promo Codes & Cash Back</h2>
            </div>
        </div>
        <div class="divborder"></div>
        <div id="store-coupons">
            <div id="coupons">
                <div class="coupon-block">
                    <ul>
                        <li>
                            <h3>Department Sale</h3>
                        </li>
                        <li>
                            <div>
                                <span class="content">
                                Shop Early Bird Online Specials for Holiday.
                                </span>
                                <span class="date"> Exp. 11/10/2016</span>
                            </div>
                        </li>
                        <li>
                            <span class="cashback">
                            + 2.0% Cash Back
                            </span>
                            <a href="<?php if ($custID == true)
							{ 
						echo 'https://discountschoolsupply.com?trunitedid='.$custID;
						} 
						else 
						{ 
					echo '#';
					} ?>" 
					target="_blank" rel="nofollow" class="button-shop">Shop Now <span class="arrow arr-right"></span></a>
                        </li>
                    </ul>
                </div>
                <div class="coupon-block">
                    <ul>
                        <li>
                            <div>
                                <span class="content">
                                'Tis the Season for Amazing Savings.
                                </span>
                                <span class="date"> Exp. 11/30/2016</span>
                            </div>
                        </li>
                        <li>
                            <span class="cashback">
                            + 2.0% Cash Back
                            </span>
                            <a href="<?php if ($custID == true)
							{ 
						echo 'https://discountschoolsupply.com?trunitedid='.$custID;
						} 
						else 
						{ 
					echo '#';
					} ?>" target="_blank" rel="nofollow" class="button-shop">Shop Now <span class="arrow arr-right"></span></a>
                        </li>
                    </ul>
                </div>
                <div class="coupon-block">
                    <ul>
                        <li>
                            <div>
                                <span class="content">
                                Find Fantastic Online Specials this Holiday.
                                </span>
                                <span class="date"> Exp. 12/26/2016</span>
                            </div>
                        </li>
                        <li>
                            <span class="cashback">
                            + 2.0% Cash Back
                            </span>
                            <a href="<?php if ($custID == true)
							{ 
						echo 'https://discountschoolsupply.com?trunitedid='.$custID;
						} 
						else 
						{ 
					echo '#';
					} ?>" target="_blank" rel="nofollow" class="button-shop">Shop Now <span class="arrow arr-right"></span></a>
                        </li>
                    </ul>
                </div>
                <div class="coupon-block">
                    <ul>
                        <li>
                            <div>
                                <span class="content">
                                Incredible Prices on Bestselling Baby Products.
                                </span>
                                <span class="date"> Exp. 11/18/2016</span>
                            </div>
                        </li>
                        <li>
                            <span class="cashback">
                            + 2.0% Cash Back
                            </span>
                            <a href="<?php if ($custID == true)
							{ 
						echo 'https://discountschoolsupply.com?trunitedid='.$custID;
						} 
						else 
						{ 
					echo '#';
					} ?>" target="_blank" rel="nofollow" class="button-shop">Shop Now <span class="arrow arr-right"></span></a>
                        </li>
                    </ul>
                </div>
                <div class="coupon-block">
                    <ul>
                        <li>
                            <div>
                                <span class="content">
                                Big Rollbacks on Window Coverings.
                                </span>
                                <span class="date"> Exp. 12/19/2016</span>
                            </div>
                        </li>
                        <li>
                            <span class="cashback">
                            + 2.0% Cash Back
                            </span>
                            <a href="<?php if ($custID == true)
							{ 
						echo 'https://discountschoolsupply.com?trunitedid='.$custID;
						} 
						else 
						{ 
					echo '#';
					} ?>" target="_blank" rel="nofollow" class="button-shop">Shop Now <span class="arrow arr-right"></span></a>
                        </li>
                    </ul>
                </div>
                <div class="coupon-block">
                    <ul>
                        <li>
                            <div>
                                <span class="content">
                                Warehouse Clear-out.
                                </span>
                                <span class="date"> Exp. 11/18/2016</span>
                            </div>
                        </li>
                        <li>
                            <span class="cashback">
                            + 2.0% Cash Back
                            </span>
                            <a href="<?php if ($custID == true)
							{ 
						echo 'https://discountschoolsupply.com?trunitedid='.$custID;
						} 
						else 
						{ 
					echo '#';
					} ?>" target="_blank" rel="nofollow" class="button-shop">Shop Now <span class="arrow arr-right"></span></a>
                        </li>
                    </ul>
                </div>
                <div class="coupon-block">
                    <ul>
                        <li>
                            <div>
                                <span class="content">
                                Huge Rollbacks on Home Decor.
                                </span>
                                <span class="date"> Exp. 11/18/2016</span>
                            </div>
                        </li>
                        <li>
                            <span class="cashback">
                            + 2.0% Cash Back
                            </span>
                            <a href="<?php if ($custID == true)
							{ 
						echo 'https://discountschoolsupply.com?trunitedid='.$custID;
						} 
						else 
						{ 
					echo '#';
					} ?>" target="_blank" rel="nofollow" class="button-shop">Shop Now <span class="arrow arr-right"></span></a>
                        </li>
                    </ul>
                </div>
                <div class="coupon-block">
                    <ul>
                        <li>
                            <div>
                                <span class="content">
                                Diaper Pack Savings.
                                </span>
                                <span class="date"> Exp. 11/18/2016</span>
                            </div>
                        </li>
                        <li>
                            <span class="cashback">
                            + 2.0% Cash Back
                            </span>
                            <a href="<?php if ($custID == true)
							{ 
						echo 'https://discountschoolsupply.com?trunitedid='.$custID;
						} 
						else 
						{ 
					echo '#';
					} ?>" target="_blank" rel="nofollow" class="button-shop">Shop Now <span class="arrow arr-right"></span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>