<?php $_product = $this->getProduct(); ?>
<?php
if(strcasecmp($_product->getSku(), Mage::helper('truwallet')->getTruWalletSku()) == 0 && Mage::helper('truwallet')->isEnableModule())
    $buttonTitle = $this->__('BUY NOW');
else
    $buttonTitle = $this->__('Add to Cart');

?>
<?php $isRequiredCondition = $_product->getData('conditional_agreements');?>
<?php $agreement = Mage::getModel('checkout/agreement')->load(1); ?>
<?php if($isRequiredCondition && $agreement->getIsActive()):?>
	<div class="product-agreement">
        <div class="agreement-content"<?php echo ($agreement->getContentHeight() ? ' style="height:' . $agreement->getContentHeight() . '"' : '')?>>
            <?php if ($agreement->getIsHtml()):?>
                <?php echo $agreement->getContent() ?>
            <?php else:?>
                <?php echo nl2br($this->escapeHtml($agreement->getContent())) ?>
            <?php endif; ?>
        </div>
        <p class="agree">
			<input type="checkbox" name="agreement[<?php echo $agreement->getId()?>]"  title="<?php echo $this->escapeHtml($agreement->getCheckboxText()) ?>" class="checkbox required-entry" />
			<label for="agreement-<?php echo $agreement->getId()?>">
				<?php echo $agreement->getIsHtml() ? $agreement->getCheckboxText() : $this->escapeHtml($agreement->getCheckboxText()) ?>
			</label>
        </p>
	</div>
<?php endif; ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <label for="qty"><?php echo $this->__('Qty:') ?></label>
        <div class="qty-holder">
            <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
            <div class="qty-changer">
                <a href="javascript:void(0)" class="qty_inc"><i class="icon-up-dir"></i></a>
                <a href="javascript:void(0)" class="qty_dec"><i class="icon-down-dir"></i></a>
            </div>
        </div>
        <?php endif; ?>
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><i class="icon-cart"></i><?php echo $buttonTitle ?></span></span></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>

<?php endif; ?>
<?php if(Mage::helper('trubox')->isCurrentCheckingCustomer()){?>
    <?php if(!Mage::helper('trubox')->isInExclusionList($_product)){?>
        <a href="<?php echo Mage::getUrl('trubox/index/addTruBox',array('id'=>$_product->getId()));?>" class="addtrubox trubox_btn" title="<?php echo $this->__('Add to TruBox') ?>">
            <img src="<?php echo $this->getSkinUrl('images/trubox-icon.png'); ?>" alt="<?php echo $this->__('Add to TruBox') ?>" /></a>
    <?php }?>
<?php }?>
<script type="text/javascript">
    $j = jQuery.noConflict();
    $j(document).ready(function(){
        var productAddToCartForm1 = new VarienForm('product_addtocart_form');
        $j('.addtrubox').click(function(){
            if(productAddToCartForm1.validator && !productAddToCartForm1.validator.validate())
            {
                return false;
            } else {
                var new_url = $j(this).attr('href')+'?'+$j('#product_addtocart_form').serialize();
                window.location.href = new_url;
            }

            return false;
        });
    });

</script>