<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Eventdiscount
 * @version    1.0.5
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="aw_eventdiscount_timer_container_<?php echo $this->getDesign();?>"
     id="aw_eventdiscount_timer_<?php echo $this->getId();?>" style="float: left;">

    <div class="aw_eventdiscount_timer_close">
        <img onclick="closeTimer(<?php echo $this->getId();?>);return false;"
             src="<?php echo $this->getSkinUrl('aw_eventdiscount/' . $this->getDesign() . '/close.png') ?>">
    </div>
    <?php if (strlen($this->getExtUrl()) > 0): ?>
<a href="<?php echo $this->getExtUrl();?>" <?php echo $this->getNewWindow();?>>
<?php endif; ?>
    <div class="aw_eventdiscount_timer" align="center">
        <div class="aw_eventdiscount_title"><?php echo $this->getTitle(); ?></div>

        <div class="aw_timer_wraper_<?php echo $this->getDesign();?>">

            <div class="aw_eventdiscount_days_container" id="test1">
                <div class="aw_eventdiscount_days">
                    <div class="aw_eventdiscount_spacer"></div>
                    <span class="aw_eventdiscount_days">01</span>
                </div>
            </div>
            <div class="aw_eventdiscount_hours_container">
                <div class="aw_eventdiscount_hours">
                    <div class="aw_eventdiscount_spacer"></div>
                    <span class="aw_eventdiscount_hours">01</span>
                </div>
            </div>

            <div class="aw_eventdiscount_separator">
                <div class="aw_eventdiscount_separator_afterhours">:</div>
                <div class="aw_eventdiscount_separator_afterhours_bottom"><span></span></div>
            </div>

            <div class="aw_eventdiscount_minutes_container">
                <div class="aw_eventdiscount_minutes">
                    <div class="aw_eventdiscount_spacer"></div>
                    <span class="aw_eventdiscount_minutes">59</span>
                </div>
            </div>

            <div class="aw_eventdiscount_separator">
                <div class="aw_eventdiscount_separator_afterminutes">:</div>
                <div class="aw_eventdiscount_separator_afterminutes_bottom"><span></span></div>
            </div>

            <div class="aw_eventdiscount_seconds_container">
                <div class="aw_eventdiscount_seconds">
                    <div class="aw_eventdiscount_spacer"></div>
                    <span class="aw_eventdiscount_seconds">30</span>
                </div>
            </div>

            <div class="aw_clear"></div>

        </div>
        <div class="aw_days"><span class="aw_eventdiscount_days_label"><?php echo $this->__('days'); ?></span></div>
        <div class="aw_hours"><span class="aw_eventdiscount_hours_label"><?php echo $this->__('hrs'); ?></span></div>
        <div class="aw_mins"><span class="aw_eventdiscount_minutes_label"><?php echo $this->__('min'); ?></span></div>
        <div class="aw_secs"><span class="aw_eventdiscount_seconds_label"><?php echo $this->__('sec'); ?></span></div>
        <div class="aw_eventdiscount_notice"><?php echo $this->getNotice(); ?></div>
    </div>
    <?php if (strlen($this->getExtUrl()) > 0): ?>
        </a>
    <?php endif; ?>
</div>
<div style="clear: both"></div>