<div class="aw_eventdiscount_timer_container_<?php echo $this->getDesign(); ?>"
     id="aw_eventdiscount_timer_<?php echo $this->getId(); ?>">
    <div class="aw_eventdiscount_timer" align="center">
        <div class="aw_eventdiscount_title"><?php echo $this->getTitle(); ?></div>
        <div class="aw_timer_wraper_<?php echo $this->getDesign(); ?>">
            <div class="aw_eventdiscount_days_container" id="aw_eventdiscount_days_container">
                <div class="aw_eventdiscount_days">
                    <div class="aw_eventdiscount_spacer"></div>
                    <span class="aw_eventdiscount_days"></span>days</div>
            </div>
            <div class="aw_eventdiscount_hours_container">
                <div class="aw_eventdiscount_hours">
                    <div class="aw_eventdiscount_spacer"></div>
                    <span class="aw_eventdiscount_hours">01</span></div>
            </div>
            <div class="aw_eventdiscount_separator">
                <div class="aw_eventdiscount_separator_afterhours">:</div>
                <div class="aw_eventdiscount_separator_afterhours_bottom"><span></span></div>
            </div>
            <div class="aw_eventdiscount_minutes_container">
                <div class="aw_eventdiscount_minutes">
                    <div class="aw_eventdiscount_spacer"></div>
                    <span class="aw_eventdiscount_minutes">59</span></div>
            </div>
            <div class="aw_eventdiscount_separator">
                <div class="aw_eventdiscount_separator_afterminutes">:</div>
                <div class="aw_eventdiscount_separator_afterminutes_bottom"><span></span></div>
            </div>
            <div class="aw_eventdiscount_seconds_container">
                <div class="aw_eventdiscount_seconds">
                    <div class="aw_eventdiscount_spacer"></div>
                    <span class="aw_eventdiscount_seconds">30</span></div>
            </div>
            <div class="aw_clear"></div>
        </div>
    </div>
</div>