<?php //echo $this->getChildHtml('sticky.nav') ?>
<?php
    $store = Mage::app()->getStore();
    $code = $store->getCode();
    $custom_block = Mage::getStoreConfig('porto_settings/header/static_block', $code);
?>
<?php echo $this->getLayout()->createBlock('eventdiscount/init')->setTemplate('aw_eventdiscount/init.phtml')->toHtml();?>
<header>
<link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <div class="head_top_bar">
        	<div class="container">
            	<div class="row">
                	<div class="head_top_in">
                    	<h6><a href="#">Click <b>HERE</b></a> to See Daily Deals</h6>
                        <div class="free_sipping">
						<!-- <img src="<?php echo $this->getSkinUrl('images/car_icon.png'); ?>" class="img-responsive" id="iconss_img"> -->
                        	<span>$99 Free Shipping</span>
                        </div>
                    </div>
                </div>
            </div>
    </div>


<div class="head_middle_bar">
        	<div class="container">
            	<div class="row">
                	<div class="bluebar_nav visible-lg visible-md visible-sm">
                    	<ul>
                        	<li class="re_move">
                            	<div class="search_blk"><?php echo $this->getChildHtml('topSearch'); ?></div>
                            </li>
                        	<li><a href="#" class="active">First Lady</a></li>
                            <li><a href="#">Contact Us</a></li>
                            <li>
                            	<ul>
                                	<li><a href="#">Shop</a></li>
                                    <li><span> | </span></li>
                                    <li><a href="#">Earn</a></li>
                                </ul>
                                <div class="clearfix"></div>
                            </li>
                            <li>
                            	<ul>
                                	<li><a href="#">Share</a></li>
                                    <li><span> | </span></li>
                                    <li><a href="#">Earn More</a></li>
                                </ul>
                                <div class="clearfix"></div>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
		
		    <div class="head_bottom_bar">
        	<div class="container">
            	<div class="row">
                	<div class="head_bottom_in">
                    	<div class="menu_block">
                        	<!--<div class="mob-menu-bar">
                            <span class="glyphicon glyphicon-menu-hamburger"></span>
                             </div>-->
							 <div class="menu_icon mob-menu-bar">
                            	<span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </div>
                        </div>
                        
                    		<div class="logo pull-left">
						 <?php 
						 //if ($this->getIsHomePage()):
						 ?>
							<h1 class="logo"><a
									href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo"><img class="desktop-logo img-responsive"
										src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>"/></a></h1>
						</div>
						 <div class="mobile_logo">
						<?php //else: ?>
							 <a href="#"><img src="<?php echo $this->getSkinUrl('images/header/mobile_logo.png'); ?>" alt="logo"></a>
						<?php //endif; ?> 
						
										
						</div>
                        <div class="head_bottom_in_rgt pull-right">
                        	<div class="orange_nav visible-lg visible-md visible-sm">
                            	<ul>
                                	<li><a href="#">BLOG</a></li>
                                    <li><a href="#">LIVE CHAT</a></li>
                                    <li><a href="#">JOIN FOR FREE</a></li>
                                    <li><a href="#">Learn How</a></li>
                                </ul>
                                <div class="clearfix"></div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="sign_in">
                            	

                            </div>
                            <nav class="visible-lg visible-md visible-sm" id ='orgmenu'>
                            	<div class = 'topMenu'><?php echo $this->getChildHtml('topMenu'); ?></div>
                                <div class="clearfix"></div>
                            </nav>
                            <div class="clearfix"></div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('mobile.nav') ?>
     <?php echo $this->getChildHtml('minicart'); ?>
	       <div class="mob_search">
        	<?php echo $this->getChildHtml('topSearch'); ?>
        </div>
</header>
<script>
jQuery(function($){
    jQuery(document).ready(function(){
        var cont =1;
        jQuery('.mob-menu-bar').click(function(){
		    // $('nav').toggle(); 
            if(cont == 1){
                jQuery('.mobile-nav').animate({
                    left: '0'
                });
                jQuery('.page').animate({
                    left: '250px'
                });
                cont = 0;
            } else {
                cont = 1;
                jQuery('.mobile-nav').animate({
                    left: '-250px'
                });
                jQuery('.page').animate({
                    left: '0'
                });
            }

        });
	
    });
    jQuery('.mobile-nav-overlay').click(function(){
		    // $('nav').toggle(); 
            alert("hola");

    });
	jQuery('.menu_block').on('click',function(){
			if(jQuery('body').hasClass('navmobileopen')){
				jQuery('body').removeClass('navmobileopen');
			}else{
				jQuery('body').addClass('navmobileopen');
			}
	});
});
</script>