<?php echo $this->getChildHtml('sticky.nav') ?>
<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $custom_block = Mage::getStoreConfig('porto_settings/header/static_block', $code);

    /* Reward Points in Header */
    $is_enable = Mage::helper('other')->enableRewardPointHeader();
    $font_size = Mage::helper('other')->getRewardFontSizeHeader();
    $text_color = Mage::helper('other')->getRewardColorHeader();
?>
<div class="header-container type6">
    <div class="top-links-container">
        <div class="top-links container">
            <?php
                $store_currency = $this->getChildHtml('store_currency');
                $store_language = $this->getChildHtml('store_language');
				$compare_link = $this->getChildHtml('compare_link');
            ?>
            <?php echo $store_currency; ?>
            <?php if($store_currency && $store_language):?>
            <span class="split"></span>
            <?php endif; ?>
            <?php echo $store_language; ?>
            <?php if(($store_currency || $store_language) && $compare_link):?>
            <span class="split"></span>
            <?php endif; ?>
			<?php echo $compare_link; ?>
            <div class="top-links-area">
                <div class="top-links-icon"><a href="javascript:void(0)"><?php echo $this->__("links"); ?></a></div>
                <?php echo $this->getChildHtml('topLinks'); ?>
            </div>
            <p class="welcome-msg"><?php echo $this->getChildHtml('welcome'); ?> <?php echo $this->getAdditionalHtml(); ?></p>
            <?php if($is_enable && Mage::getSingleton('customer/session')->isLoggedIn()){?>
            <div class="reward-top-header">
                <ul class="award-header">
                    <li><?php echo Mage::helper('other')->__('YTD PAYOUT: %s',Mage::helper('other')->ytd());?></li>
                    <li><?php echo Mage::helper('other')->__('MTD POOL: %s',Mage::helper('other')->mtd());?></li>
                </ul>
            </div>
            <?php }?>
            <div class="clearer"></div>
        </div>
    </div>
    <div class="header container">
        <?php if ($this->getIsHomePage()):?>
        <h1 class="logo"><strong><?php echo $this->getLogoAlt(); ?></strong><a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo"><img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" /></a></h1>
        <?php else:?>
        <a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo"><strong><?php echo $this->getLogoAlt(); ?></strong><img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" /></a>
        <?php endif; ?>
        <div class="cart-area">
            <?php echo '<div class="custom-block">'.$this->getLayout()->createBlock('cms/block')->setBlockId($custom_block)->toHtml().'</div>'; ?>
            <?php echo $this->getChildHtml('minicart'); ?>
        </div>
        <div class="menu-icon"><a href="javascript:void(0)" title="<?php echo $this->__('Menu'); ?>"><i class="fa fa-bars"></i></a></div>
        <div class="search-area">
            <a href="javascript:void(0)" class="search-icon"><i class="icon-search"></i></a>
            <?php echo $this->getChildHtml('topSearch'); ?>
        </div>
        <?php echo $this->getChildHtml('topMenu') ?>
        <?php echo $this->getChildHtml("demo_header_tooltip"); ?>
    </div>
</div>
<?php echo $this->getChildHtml('mobile.nav') ?>
<?php if($is_enable && Mage::getSingleton('customer/session')->isLoggedIn()){?>
<style type="text/css">
    .reward-top-header ul.award-header li
    {
        font-size: <?php echo $font_size;?>px;
        color: #<?php echo $text_color;?>;
    }
</style>
<?php }?>
