<?php //echo $this->getChildHtml('sticky.nav') ?>
<?php
    $store = Mage::app()->getStore();
    $code = $store->getCode();
    $custom_block = Mage::getStoreConfig('porto_settings/header/static_block', $code);
?>
<?php echo $this->getLayout()->createBlock('eventdiscount/init')->setTemplate('aw_eventdiscount/init.phtml')->toHtml();?>
  <header>
   <div class="top-notification">
    <div class="container">
      <p><a href="#">Click <b>HERE</b> <span>to See Daily Deals</span></a></p>
      <div class="shipping-info">
        <img src="http://dev.trunited.com/skin/frontend/smartwave/porto_trunited/images/icon-truck.png" class="img-responsive">
        <span>$99 Free Shipping</span>
      </div>
    </div>
  </div>
<div class="middle-bar hidden-xs hidden-sm">
  <div class="container">
    <ul>
      <li>
        <a href="#">
            First Lady
        </a>
          <a href="#">
           <div class="link-addon">
            <span>blog</span>
          </div>    
        </a>
      </li>
      <li>
        <a href="#">
            Contact Us
         </a>
          <a href="#">
           <div class="link-addon">
            <span>live chat</span>
          </div>    
        </a>
      </li>
      <li>
        <a href="#">
            Shop | Earn 
        </a>
          <a href="#">
           <div class="link-addon">
            <span>join for free</span>
          </div>    
        </a>
      </li>
      <li>
        <a href="#">
            Share | Earn More 
        </a>
          <a href="#">
           <div class="link-addon">
            <span>learn how</span>
          </div>    
        </a>
      </li>
    </ul>
  </div>
</div>
<div class="container">
    <div class="searchForm">
        <?php echo $this->getChildHtml('topSearch'); ?>
    </div>
</div>
<nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
<!-- BOTON DE MENU
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
-->
<!--
        <a href="#"><img src="./images/logo.png" class="desktop-logo img-responsive"></a>
        <a href="#"><img src="./images/logo-mobile.png" class="mobile-logo img-responsive"></a>
-->
       <div class="mob-menu-bar">
           <span class="glyphicon glyphicon-menu-hamburger"></span>
       </div>
        <?php if ($this->getIsHomePage()): ?>
            <h1 class="logo"><a
                    href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo"><img class="desktop-logo img-responsive"
                        src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>"/></a></h1>
        <?php else: ?>
            <h1><a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>"
               class="logo"><img class="desktop-logo img-responsive"
                                 src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>"/><img src="skin/frontend/smartwave/porto_trunited/images/logo-mobile.png" class="mobile-logo img-responsive" alt="<?php echo $this->getLogoAlt(); ?>"/></a></h1>
        <?php endif; ?>  
      </div>
<!--
      <div class="collapse navbar-collapse" id="main-menu">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Home</a></li>
          <li><a href="#">Shop</a></li>
          <li><a href="#">Global Brands</a></li>
          <li><a href="#">Gift Card Shop</a></li>
          <li class="sign-in-link"><a href="#">Sign In</a></li>
          <li class="cart-wrapper hidden-xs">
            <a href="#">
              Cart 
              <div class="desktop-cart">
                <div class="itmes-count">2</div>
              </div>
            </a>
          </li>
        </ul>        
      </div>
-->
<!--
 <div class="menu-icon"><a href="javascript:void(0)" title="<?php echo $this->__('Menu'); ?>"><i
                    class="fa fa-bars"></i></a></div>
-->
<?php echo $this->getChildHtml('topMenu'); ?>
<!--      <div class="mobile-cart">-->
<!--        <div class="itmes-count">2</div>-->
        <?php echo $this->getChildHtml('minicart'); ?>
<!--      </div>-->


        <?php echo $this->getChildHtml('mobile.nav') ?>
    </div>
  </nav>
</header>
<script>
jQuery(function($){
    $(document).ready(function(){
        var cont =1;
        $('.mob-menu-bar').click(function(){
		    // $('nav').toggle(); 
            if(cont == 1){
                $('.mobile-nav').animate({
                    left: '0'
                });
                $('.page').animate({
                    left: '250px'
                });
                cont = 0;
            } else {
                cont = 1;
                $('.mobile-nav').animate({
                    left: '-250px'
                });
                $('.page').animate({
                    left: '0'
                });
            }

        });
    });
    $('.mobile-nav-overlay').click(function(){
		    // $('nav').toggle(); 
            alert("hola");

    });
});
</script>