<?php
$is_enable = Mage::helper('custompromotions/verify')->isEnable();
$is_phone = Mage::getSingleton('core/session')->getPhoneActive();
$is_code = Mage::getSingleton('core/session')->getCodeActive();
$is_verify = Mage::getSingleton('core/session')->getVerify();
$phone_collection = Mage::getModel('custompromotions/phonecode')->getCollection()
                        ->addFieldToSelect('id')
                        ->addFieldToSelect('nicename')
                        ->addFieldToSelect('phonecode')
                        ->setOrder('id','asc')
                    ;
?>
<?php if($is_enable){?>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/magestore/jquery-ui.css')?>">
<script type="text/javascript">
    $j = jQuery.noConflict();
    $j( function() {
        $j.widget( "custom.combobox", {
            _create: function() {
                this.wrapper = $j( "<span>" )
                    .addClass( "custom-combobox" )
                    .insertAfter( this.element );

                this.element.hide();
                this._createAutocomplete();
                this._createShowAllButton();
            },

            _createAutocomplete: function() {
                var selected = this.element.children( ":selected" ),
                    value = selected.val() ? selected.text() : "";

                this.input = $j( "<input>" )
                    .appendTo( this.wrapper )
                    .val( value )
                    .attr( "title", "" )
                    .addClass( "custom-combobox-input ui-widget ui-widget-content ui-state-default ui-corner-left input-text required-entry" )
                    .autocomplete({
                        delay: 0,
                        minLength: 0,
                        source: $j.proxy( this, "_source" )
                    })
                    .tooltip({
                        classes: {
                            "ui-tooltip": "ui-state-highlight"
                        }
                    });

                this._on( this.input, {
                    autocompleteselect: function( event, ui ) {
                        ui.item.option.selected = true;
                        this._trigger( "select", event, {
                            item: ui.item.option
                        });
                    },

                    autocompletechange: "_removeIfInvalid"
                });
            },

            _createShowAllButton: function() {
                var input = this.input,
                    wasOpen = false;

                $j( "<a>" )
                    .attr( "tabIndex", -1 )
                    .attr( "title", "Show All Items" )
                    .tooltip()
                    .appendTo( this.wrapper )
                    .button({
                        icons: {
                            primary: "ui-icon-triangle-1-s"
                        },
                        text: false
                    })
                    .removeClass( "ui-corner-all" )
                    .addClass( "custom-combobox-toggle ui-corner-right combobox-showall" )
                    .on( "mousedown", function() {
                        wasOpen = input.autocomplete( "widget" ).is( ":visible" );
                    })
                    .on( "click", function() {
                        input.trigger( "focus" );

                        // Close if already visible
                        if ( wasOpen ) {
                            return;
                        }

                        // Pass empty string as value to search for, displaying all results
                        input.autocomplete( "search", "" );
                    });
            },

            _source: function( request, response ) {
                var matcher = new RegExp( $j.ui.autocomplete.escapeRegex(request.term), "i" );
                response( this.element.children( "option" ).map(function() {
                    var text = $j( this ).text();
                    if ( this.value && ( !request.term || matcher.test(text) ) )
                        return {
                            label: text,
                            value: text,
                            option: this
                        };
                }) );
            },

            _removeIfInvalid: function( event, ui ) {

                // Selected an item, nothing to do
                if ( ui.item ) {
                    return;
                }

                // Search for a match (case-insensitive)
                var value = this.input.val(),
                    valueLowerCase = value.toLowerCase(),
                    valid = false;
                this.element.children( "option" ).each(function() {
                    if ( $j( this ).text().toLowerCase() === valueLowerCase ) {
                        this.selected = valid = true;
                        return false;
                    }
                });

                // Found a match, nothing to do
                if ( valid ) {
                    return;
                }

                // Remove invalid value
                this.input
                    .val( "" )
                    .attr( "title", value + " didn't match any item" )
                    .tooltip( "open" );
                this.element.val( "" );
                this._delay(function() {
                    this.input.tooltip( "close" ).attr( "title", "" );
                }, 2500 );
                this.input.autocomplete( "instance" ).term = "";
            },

            _destroy: function() {
                this.wrapper.remove();
                this.element.show();
            }
        });

        $j( "#combobox" ).combobox();
        $j('.custom-combobox-input').attr('placeholder','<?php echo $this->__('Enter your country');?>');
    });
</script>
<?php }?>
<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php if($is_enable && $is_verify == null){?>
        <?php if($is_code == null || $is_phone == null){?>
            <form action="<?php echo Mage::getUrl('custompromotions/customer/sendCode')?>"
                  method="post" id="verify_customer_mobile">
                <div class="fieldset verify_mobile">
                    <h2 class="legend"><?php echo $this->__('VERIFY YOU ARE HUMAN') ?></h2>
                    <ul class="form-list">
                        <li class="fields">
                            <div class="field">
                                <label for="phone_number" class="required"><em>*</em><?php echo $this->__('Enter your phone number') ?></label>
<!--                                <div class="input-box pprefix ui-widget">-->
<!--                                    <select id="combobox" name="phone_prefix">-->
<!--                                        <option value=""></option>-->
<!--                                        --><?php //if(sizeof($phone_collection) > 0){?>
<!--                                            --><?php //foreach($phone_collection as $phone){?>
<!--                                                <option value="--><?php //echo $phone->getPhonecode();?><!--">--><?php //echo $phone->getNicename().' (+'.$phone->getPhonecode().')';?><!--</option>-->
<!--                                            --><?php //}?>
<!--                                        --><?php //}?>
<!--                                    </select>-->
<!--                                </div>-->
                                <div class="input-box">
                                    <input type="text" name="phone_number" id="phone_number" title="<?php echo $this->__('Enter your phone') ?>" class="input-text required-entry validate-phoneStrict"
                                        placeholder="<?php echo $this->__('Enter your phone number')?>"/>
                                    <em><?php echo $this->__('You have to verify your mobile before registering.');?></em>
                                </div>

                            </div>
                            <div class="field">
                                <div class="input-box send_code">
                                    <button type="submit" title="<?php echo $this->__('Send Code') ?>" class="button"><span><span><?php echo $this->__('Send Code') ?></span></span></button>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </form>
        <?php } else {?>
            <form action="<?php echo Mage::getUrl('custompromotions/customer/verifyCode')?>"
                  method="post" id="verify_code_mobile">
                <div class="fieldset verify_mobile">
                    <h2 class="legend"><?php echo $this->__('VERIFY YOU ARE HUMAN') ?></h2>
                    <ul class="form-list">
                        <li class="fields">
                            <div class="field">
                                <label for="verify_code" class="required"><em>*</em><?php echo $this->__('Please enter your verification code') ?></label>
                                <div class="input-box">
                                    <input type="text" name="verify_code" id="verify_code" title="<?php echo $this->__('Enter verification code') ?>" class="input-text required-entry"
                                           placeholder="<?php echo $this->__('Enter verification code')?>"/>
                                </div>
                            </div>
                            <div class="field">
                                <label for="submit"></label>
                                <div class="input-box">
                                    <button type="submit" title="<?php echo $this->__('Verify Code') ?>" class="button"><span><span><?php echo $this->__('Verify Code') ?></span></span></button>
                                </div>
                            </div>

                        </li>
                    </ul>
                    <div style="clear: both"></div>
                    <div class="field">
                        <a href="<?php echo Mage::getUrl('custompromotions/customer/back')?>"
                           title="Back to enter mobile number"><?php echo $this->__('START OVER');?></a>
                    </div>
                </div>
            </form>
        <?php }?>
    <?php }?>
    <?php if(!$is_enable || ($is_enable && $is_phone != null && $is_code != null && $is_verify != null)){?>
        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
            <div><?php echo $this->__('Click <a href="'.Mage::getUrl('custompromotions/customer/back').'">here</a> to verify your mobile again');?> </div>
            <br />
            <div class="fieldset">
                <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
                <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
                <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>

                <ul class="form-list">
                    <li class="fields">
                        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                    </li>
                    <li class="wide">
                        <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                        </div>
                    </li>
                    <?php if ($this->isNewsletterEnabled()): ?>
                    <li class="control">
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                        <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                    </li>
                    <?php endif ?>
                <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                <?php if ($_dob->isEnabled()): ?>
                    <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
                <?php endif ?>
                <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                <?php if ($_taxvat->isEnabled()): ?>
                    <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
                <?php endif ?>
                <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                <?php if ($_gender->isEnabled()): ?>
                    <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
                <?php endif ?>
                </ul>
            </div>
        <?php if($this->getShowAddressFields()): ?>
            <div class="fieldset">
                <input type="hidden" name="create_address" value="1" />
                <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
                <ul class="form-list">
                    <li class="fields">
                        <div class="field">
                            <label for="company"><?php echo $this->__('Company') ?></label>
                            <div class="input-box">
                                <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                            <div class="input-box">
                                <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                            </div>
                        </div>
                    </li>
                <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                    <li class="wide">
                        <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?> 1" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <li class="wide">
                        <label for="street_<?php echo $_i; ?>"><?php echo $this->__('Street Address %s', $_i) ?></label>
                        <div class="input-box">
                            <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
                <?php endfor; ?>
                    <li class="fields">
                        <div class="field">
                            <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                            <div class="input-box">
                                <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                            <div class="input-box">
                                <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                                //]]>
                                </script>
                                <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                            <div class="input-box">
                                <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                            </div>
                        </div>
                        <div class="field">
                            <div class="input-box">
                                <label for="country" class="required"><i class="icon-country"></i><?php echo $this->__('Country') ?><em>*</em></label>
                                <?php echo $this->getCountryHtmlSelect() ?>
                            </div>
                        </div>
                    </li>
                </ul>
                <input type="hidden" name="default_billing" value="1" />
                <input type="hidden" name="default_shipping" value="1" />
            </div>
        <?php endif; ?>
            <div class="fieldset">
                <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
                <ul class="form-list">
                    <li class="fields">
                        <div class="field">
                            <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                            </div>
                        </div>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                    <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                </ul>
                <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
            </div>
            <div class="buttons-set">
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
                <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
            </div>
            <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                <input name="context" type="hidden" value="checkout" />
            <?php endif; ?>
        </form>
    <?php }?>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        var verifyForm = new VarienForm('verify_customer_mobile', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
</div>
