<ol>
    <li class="trunited-discounts">
        <h3 style="float:left" id="trunited_discounts_step_header" class="step_5">
            <?php echo $this->__('Trunited Discounts'); ?>
        </h3>
        <div class="ajax-loader5" id="ajax-trunited-discounts"
             style="display:none; float: left; margin-top: 14px; margin-left: 10px;"></div>
        <div class="clear"></div>
        <div id="onestepcheckout-trunited-discounts" class="onestepcheckout-trunited-discounts">
            <?php if(Mage::helper('trugiftcard')->isShowTruWallet()){?>
                <?php echo $this->getLayout()->createBlock('truwallet/payment_form')->renderView();?>
            <?php }?>
            <?php if(Mage::helper('trugiftcard')->isShowTruGiftCard()){?>
                <?php echo $this->getLayout()->createBlock('trugiftcard/payment_form')->renderView();?>
            <?php }?>
        </div>
        <div id="control_overlay_trunited_discounts"
             style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; z-index: 9998; display: none;">
        </div>
    </li>

</ol>