<?php
/**
 * Referers history template
 */
?>
<?php
$store_id = Mage::app()->getStore()->getStoreId();
$check_responsvie = Mage::getStoreConfig('affiliateplus/style_config/responsive_enable', $store_id);
 if($check_responsvie)
     $class_name = 'col-lg-9 col-md-9 col-sm-12 col-xs-12';
 else
     $class_name = 'col-lg-9 col-md-9 col-sm-9 col-xs-9';

$parameter = $this->getUrlParameter();
?>

<div class="aff-main-content <?php echo $class_name; ?>">
    <div class="aff-title">
        <h2><?php echo $this->__('Connect Friends and Earn More Reward Points') ?></h2>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <ul class="message" id="affiliate-facebook-msg" style="display:none;">
        <li class="success-msg">
            <ul><li><?php echo $this->__('This message has been posted successfully.') ?></li></ul>
        </li>
    </ul>
    <div class="aff-refer">
        <div style="margin-bottom: 18px;">
            <?php echo $this->getReferDescription() ?>
        </div>

        <div class="aff-title"></div>

        <?php $trafficSources = $this->getTrafficSources() ?>
    </div>
    <div id="affiliateplus-sidebar" class="col-right sidebar col-xs-6 col-md-4">
        <div class="block block-list">
            <div class="block-title">
                <strong><?php echo $this->__('Personal URL') ?></strong>
            </div>
            <div class="block-content">
                <form id="affiliate-personal-url-form" method="post" action="<?php echo $this->getUrl('*/*/personal') ?>">
                    <div id="affiliate-opc-personal-url" class="step a-item">
                        <ul class="form-list">
                            <li class="control">
                                <label for="use-personal-url"><?php echo $this->__('Your Affiliate Parameter') ?></label>
                                <div class="actions identify_code">
                                    <?php echo '?' . $parameter?>
                                </div>
                                <div class="guide"><?php echo $this->getUrlParameterDescription();?></div>
                            </li>
                            <!--customize by viet -->
                            <li class="control">
                                <label for="use-personal-url"><?php echo $this->__('Email') ?></label>
                                <div class="actions">
                                    <a id="personal_affiliate_url_email_quick" title="<?php echo $this->__('Your personal affiliate URL') ?>"></a>
                                </div>
                            </li>
                            <!--customize by viet -->
                            <li class="control">
                                <input type="checkbox"<?php if ($this->getCustomUrl()): ?> checked="true"<?php endif ?> id="use-personal-url" value="1" class="required-entry" onclick="changePersonalUrl(this);" />
                                <label for="use-personal-url"><?php echo $this->__('Custom') ?></label>
                                <div class="input-box" id="input-personal-url"<?php if (!$this->getCustomUrl()): ?> style="display:none;"<?php endif ?>>
                                    <input class ="required-entry form-control" type="text" id="personal_url" name="personal_url" onchange="changeCustomUrl();" onkeyup="changeCustomUrl();" value="<?php echo $this->getCustomUrl() ?>" class="input-text required-entry"/>
                                </div>
                            </li>
                        </ul>
                        <div class="buttons-set" id="button-save-personal-url"<?php if (!$this->getCustomUrl()): ?> style="display:none;"<?php endif ?>>
                            <button type="submit" title="<?php echo $this->__('Save'); ?>" class="button button-config">
                                <span>
                                    <span><?php echo $this->__('Save') ?></span>
                                </span>
                            </button>
                        </div>
                    </div>
                </form>
                <div class="actions">
                    <a id="personal_affiliate_url" title="<?php echo $this->__('Your personal affiliate URL') ?>"></a>
                </div>
                <script type="text/javascript">
                    var personalUrlForm = new VarienForm('affiliate-personal-url-form', true);
                    function changePersonalUrl(el) {
                        if (el.checked) {
                            $('input-personal-url').show();
                            $('button-save-personal-url').show();
                            changeCustomUrl();
                        } else {
                            $('input-personal-url').hide();
                            $('button-save-personal-url').hide();
                            var personalUrl = '<?php echo $this->getPersonalUrl() ?>';
                            var urlEl = $('personal_affiliate_url');
                            if (urlEl.href != personalUrl) {
                                urlEl.href = personalUrl;
                                urlEl.innerHTML = prepareShowPersonalUrl(personalUrl, 54);
                            }
                            var personalUrlFixedEmail = '<?php echo Mage::helper('affiliateplus/account')->getReferEmailUrl() ?>';
                            var urlFixedEmail = $('personal_affiliate_url_email_quick');
                            if (urlFixedEmail.href != personalUrlFixedEmail) {
                                urlFixedEmail.href = personalUrlFixedEmail;
                                urlFixedEmail.innerHTML = prepareShowPersonalUrl(personalUrlFixedEmail, 54);
                            }
                        }
                    }
                    var process = 1;
                    function changeCustomUrl() {
                        if (process) {
                            process = 0;
                            var customUrlInput = $('personal_url').value;
                            customUrlInput = customUrlInput.toLowerCase();
                            var url = '<?php echo $this->getUrl('affiliateplus/refer/refineCustomUrl') ?>' + '?custom_url=' + customUrlInput;
                            var request = new Ajax.Request(url, {
                                onComplete: function(response) {
                                    var customUrl = JSON.parse(response.responseText);
                                    var personalUrl = '';
                                    if (customUrl == '') {
                                        personalUrl = '<?php echo $this->getPersonalUrl() ?>';
                                    } else {
                                        var prefixUrl = '<?php echo $this->getPrefixUrl() ?>';
                                        personalUrl = prefixUrl + customUrl;
                                        var urlInStore = '<?php echo $this->getSuffixUrl() ?>';
                                        if (urlInStore.search('[?]') != -1)
                                            personalUrl += '?' + urlInStore.split('?')[1];
                                    }
                                    var urlEl = $('personal_affiliate_url');
                                    if (urlEl.href != personalUrl) {
                                        urlEl.href = personalUrl;
                                        urlEl.innerHTML = prepareShowPersonalUrl(personalUrl, 54);
                                    }
                                    var personalUrlFixedEmail = '<?php echo Mage::helper('affiliateplus/account')->getReferEmailUrl() ?>';
                                    var urlFixedEmail = $('personal_affiliate_url_email_quick');
                                    if (urlFixedEmail.href != personalUrlFixedEmail) {
                                        urlFixedEmail.href = personalUrlFixedEmail;
                                        urlFixedEmail.innerHTML = prepareShowPersonalUrl(personalUrlFixedEmail, 54);
                                    }
                                }
                            }
                            );
                            process = 1;
                        }
                    }
                    function prepareShowPersonalUrl(pUrl, len) {
                        var newPUrl = '';
                        var i;
                        for (i = 0; i < pUrl.length - len; i += len)
                            newPUrl += pUrl.substr(i, len) + ' ';
                        newPUrl += pUrl.substr(i);
                        return newPUrl;
                    }
                    changePersonalUrl($('use-personal-url'));
                </script>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        function toggleGooglePlus() {
            toggleAffiliateRighbox('affiliate-opc-google-content');
            if (loadGooglePlus) {
                (function() {
                    var po = document.createElement('script');
                    po.type = 'text/javascript';
                    po.async = true;
                    po.src = 'https://apis.google.com/js/plusone.js';
                    var s = document.getElementsByTagName('script')[0];
                    s.parentNode.insertBefore(po, s);
                })();
                loadGooglePlus = false;
            }
        }
        var affiliateCurrentEId = '';
        function toggleAffiliateRighbox(eId) {
            if (eId != affiliateCurrentEId) {
                if (affiliateCurrentEId != '') {
                    $(affiliateCurrentEId).hide();
                    $($(affiliateCurrentEId).parentNode.id).removeClassName('active');
                }
                affiliateCurrentEId = eId;
            }
            $(eId).toggle();
            $($(eId).parentNode.id).toggleClassName('active');
        }

        function getPopupPosition(width, height) {
            var screenX = typeof window.screenX != 'undefined' ? window.screenX : window.screenLeft;
            var screenY = typeof window.screenY != 'undefined' ? window.screenY : window.screenTop;
            var outerWidth = typeof window.outerWidth != 'undefined' ? window.outerWidth : document.body.clientWidth;
            var outerHeight = typeof window.outerHeight != 'undefined' ? window.outerHeight : (document.body.clientHeight - 22);
            var left = parseInt(screenX + ((outerWidth - width) / 2), 10);
            var top = parseInt(screenY + ((outerHeight - height) / 2.5), 10);
            return 'width=' + width + ',height=' + height + ',left=' + left + ',top=' + top;
        }
    </script>
</div>
