<?php 
    $postData = Mage::app()->getRequest()->getParam('alpha');
    $keywordData = Mage::app()->getRequest()->getParam('quick_keyword');
?>
<div class="toolbar">
    <?php if( $this->isExpanded() ): ?>
    <div class="sorter">
        <div class="sort-by">
            <label><?php echo $this->__('Sort By') ?></label>
            <select onchange="setLocation(this.value)">
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                <option value="<?php echo $this->getNewUrl($postData, $keywordData, $this->getOrderUrl($_key, 'asc'))?>"
                    <?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                    <?php echo $this->__($_order) ?>
                </option>
            <?php endforeach; ?>
            </select>
        </div>
    </div>
    <?php endif; ?>
</div>
